### ISSUE TITLE
Can't set settings through groovy because there are no setters

### ISSUE THREAD

**Issue by daften** [jenkinsci/slack-plugin#116]
See e.g. https://github.com/jenkinsci/mailer-plugin/blob/master/src/main/java/hudson/tasks/Mailer.java
That config can be set from Groovy because there are setters there.

Error message:

```
STDERR: groovy.lang.MissingMethodException: No signature of method: jenkins.plugins.slack.SlackNotifier$DescriptorImpl.setTeamDomain() is applicable for argument types: (java.lang.String) values: [...]

==> default: Possible solutions: getTeamDomain()
==> default:    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
==> default:    at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
==> default:    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
==> default:    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
==> default:    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
==> default:    at RemoteClass.run(RemoteClass:9)
==> default:    at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:266)
==> default:    at groovy.lang.GroovyShell.run(GroovyShell.java:517)
==> default:    at hudson.cli.GroovyCommand.run(GroovyCommand.java:94)
==> default:    at hudson.cli.CLICommand.main(CLICommand.java:237)
==> default:    at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
==> default:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
==> default:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
==> default:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
==> default:    at java.lang.reflect.Method.invoke(Method.java:606)
==> default:    at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:326)
==> default:    at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:301)
==> default:    at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:260)
==> default:    at hudson.remoting.UserRequest.perform(UserRequest.java:121)
==> default:    at hudson.remoting.UserRequest.perform(UserRequest.java:49)
==> default:    at hudson.remoting.Request$2.run(Request.java:325)
==> default:    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
==> default:    at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
==> default:    at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
==> default:    at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
==> default:    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
==> default:    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
==> default:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
==> default:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
==> default:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by samrocketman** [comment]
See #23 for a solution.

**Comment by samrocketman** [comment]
Also, contributions are welcome.  I don't actively develop this plugin.  I only maintain pull requests and releases.  I agree setters and getters would be a good thing to have.

**Comment by timja** [comment]
See
https://github.com/jenkinsci/slack-plugin/issues/23
https://github.com/jenkinsci/slack-plugin/issues/427#issuecomment-444024289
https://github.com/jenkinsci/slack-plugin#configuration-as-code
