### ISSUE TITLE
Job "Test Connection" throws false negatives.

### ISSUE THREAD

**Issue by yoyobbi** [jenkinsci/slack-plugin#132]
With version 1.8 of the Slack Notification plugin, I have the opposite problem to [issue 51](https://github.com/jenkinsci/slack-plugin/issues/51) -- the "Test Connection" button from a project configuration page indicates a failed connect, even on a project which is successfully posting notifications to slack. The project does not override the global slack config. "Test Connection" from global config succeeds.

**Comment by samrocketman** [comment]
Please provide the exact steps in which I can reproduce this issue.  I'm not able to currently reproduce the behavior you describe from the master branch.

**Comment by yoyobbi** [comment]
- Select any project.
- Click Configuration.
- Expand the Advanced section of the Slack configuration.
- Click Test Connection.
- The "testing" spinner shows for a few seconds.
- Then the red Failure indication appears.

I'm using Slack plugin version 1.8 with Jenkins 1.609.1.

**Comment by samrocketman** [comment]
I'm still not able to replicate the behavior.  I bootstrapped slack with Jenkins 1.609.1 with [these specific plugin versions][plugins] (includes slack plugin 1.8).  I can't replicate the "false positive" behavior.  Even when the spinner appears it doesn't post to slack when it displays a failure.

* When failures occur no messages are published to slack.
* When success occurs messages are published to slack.

Feel free to try bootstrapping slack yourself and adjust plugin versions to more closely match your environment.  That bootstrapped Jenkins is pre-configured to post against the project [jenkins-slack-plugin test slack instance][slack].  You can [sign up for it here][signup].

If you can replicate it reliably then please tell me how.  Otherwise I'll close this issue after a week or so if you don't respond.

[plugins]: https://github.com/samrocketman/jenkins-bootstrap-slack/blob/c26683d277fd8608c514eec0be3b24d78b19e731/build.gradle#L52-L83
[signup]: https://jenkins-slack-testing-signup.herokuapp.com/
[slack]: https://jenkins-slack-plugin.slack.com/

**Comment by samrocketman** [comment]
I can't replicate this issue with the provided steps and since there hasn't been an update on how to replicate the issue this is being closed.

**Comment by bradical** [comment]
I'm running into the same issue described here v1.8.1 of the Slack plugin in Jenkins ver. 1.642.1. Seems like the project level fields which are supposed to only be overrides are somehow **always** being used.

I have the Global Slack Notifier settings configured and the Test Connection from Jenkins Configure System works fine.

But when I run Test Connection from my project which doesn't override any of those settings:

![image](https://cloud.githubusercontent.com/assets/191132/12987113/a5567108-d0c8-11e5-98ec-601292635e4d.png)

I get a test failure basically saying it's missing a domain:

```
Feb 11, 2016 2:04:42 PM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting: to  on  using https://.slack.com/services/hooks/jenkins-ci?token=: Slack/Jenkins plugin: you're all set. good
Feb 11, 2016 2:04:42 PM jenkins.plugins.slack.StandardSlackService publish
WARNING: Error posting to Slack
java.net.UnknownHostException: .slack.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:407)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
	at hudson.util.NoClientBindSSLProtocolSocketFactory.createSocket(NoClientBindSSLProtocolSocketFactory.java:135)
	at hudson.util.NoClientBindSSLProtocolSocketFactory.createSocket(NoClientBindSSLProtocolSocketFactory.java:117)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:72)
	at jenkins.plugins.slack.SlackNotifier$SlackJobProperty$DescriptorImpl.doTestConnection(SlackNotifier.java:397)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Feb 11, 2016 2:04:42 PM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting succeeded
```

**Comment by bradical** [comment]
Then, even after I do copy over the same settings from Global and get the Test Connection to pass, I can't seem to get the notification hooks to deliver any messages to Slack. Only the Test message ever goes through. No failures in the log when it fails to deliver anything to slack for build events.

**Comment by bradical** [comment]
Ah ok, I figured the issue where it wasn't sending notifications once the Test Connection at the project-level was working. Needed to RFTM and [add the post-build actions to my builds](https://wiki.jenkins-ci.org/display/JENKINS/Slack+Plugin#SlackPlugin-PostbuildActions) in addition to checking the boxes at the top.

And, in fact, the notifications do work if I leave the domain, channel, token fields blank at the project level.

I think the only confusion at this point was that the "Test Connection" at the project level was a "Failure" when there blank even though the notifications did in fact work. I'm guessing the Test Connection is pulling from the project-level fields but the actual notifications know to inherit from the Global settings. So it's really just a false-positive on the Test Connection failure at the project level. And the fact that I hadn't added the post-build steps made it seem like the whole plugin wasn't working.
