### ISSUE TITLE
InvalidAlgorithmParameterException inside generateECKeyPair during publish

### ISSUE THREAD

**Issue by Leander1P** [jenkinsci/slack-plugin#141]
Assuming this is a java version issue, not directly related to slack-plugin, but could use any help with next steps for diagnosis.  Feel free to redirect if here is not an appropriate place for this.

We recently upgraded to icedtea-7.2.6.1, tomcat 8.0.23-gentoo, and Jenkins LTS 1.625.1, with Slack Notification Plugin 1.8.  We now get an `InvalidAlgorithmParameterException` inside `generateECKeyPair`, seemingly related to setting up a SSL/TLS connection to slack.com.  I've pasted this in below, along with some version info.

I presume this is somehow failing to degrade to a supported cipher type or strength or similar (where a previous icedtea-6+tomcat-7 install did).

Initial search-fu is failing me -- most `InvalidAlgorithmParameterException` docs seem to be about CA chains being broken (I don't think this is, based on the stack -- seems more likely this is related to ECDHE curve setup or similar).

It seems like it may be possible to decorate the HttpClient to force it to use a different cipher suite / TLS level / similar and rebuild the plugin, but I'm not entirely certain this is the best route to pursue.  Also wondering if we could get a different JSSE impl or similar.

Any suggestions as to where to start would be appreciated.

```text
20-Oct-2015 12:06:13.800 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.23-gentoo
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Oct 19 2015 20:30:49 UTC
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.23
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.8.13-gentoo
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/icedtea-bin-7.2.6.1/jre
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.7.0_85-b01
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat-8
20-Oct-2015 12:06:13.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat-8
20-Oct-2015 12:06:13.803 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
20-Oct-2015 12:06:13.803 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat-8/conf/logging.properties
20-Oct-2015 12:06:13.803 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat-8
20-Oct-2015 12:06:13.803 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat-8
20-Oct-2015 12:06:13.803 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/var/tmp/tomcat-8

[...]

20-Oct-2015 13:19:53.131 INFO [Handling POST /descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.3.78 : ajp-nio-8009-exec-7] jenkins.plugins.slack.StandardSlackService.publish Posting: to  on exampleteam using https://exampleteam.slack.com/services/hooks/jenkins-ci?token=exampletoken: Slack/Jenkins plugin: you're all set on / green
20-Oct-2015 13:19:53.207 INFO [Handling POST /descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.3.78 : ajp-nio-8009-exec-7] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry I/O exception (javax.net.ssl.SSLException) caught when processing request: java.security.ProviderException: java.security.InvalidAlgorithmParameterException
20-Oct-2015 13:19:53.207 INFO [Handling POST /descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.3.78 : ajp-nio-8009-exec-7] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry Retrying request
20-Oct-2015 13:19:53.245 INFO [Handling POST /descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.3.78 : ajp-nio-8009-exec-7] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry I/O exception (javax.net.ssl.SSLException) caught when processing request: java.security.ProviderException: java.security.InvalidAlgorithmParameterException
20-Oct-2015 13:19:53.245 INFO [Handling POST /descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.3.78 : ajp-nio-8009-exec-7] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry Retrying request
20-Oct-2015 13:19:53.287 INFO [Handling POST /descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.3.78 : ajp-nio-8009-exec-7] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry I/O exception (javax.net.ssl.SSLException) caught when processing request: java.security.ProviderException: java.security.InvalidAlgorithmParameterException
20-Oct-2015 13:19:53.288 INFO [Handling POST /descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.3.78 : ajp-nio-8009-exec-7] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry Retrying request
20-Oct-2015 13:19:53.322 WARNING [Handling POST /descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.3.78 : ajp-nio-8009-exec-7] jenkins.plugins.slack.StandardSlackService.publish Error posting to Slack
 javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidAlgorithmParameterException
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1783)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:127)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:506)
        at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:66)
        at jenkins.plugins.slack.SlackNotifier$DescriptorImpl.doTestConnection(SlackNotifier.java:210)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
        at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
        at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:95)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:129)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:86)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:73)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
        at org.apache.catalina.core.StandardWrapperValve.invoke(Unknown Source)
        at org.apache.catalina.core.StandardContextValve.invoke(Unknown Source)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Unknown Source)
        at org.apache.catalina.core.StandardHostValve.invoke(Unknown Source)
        at org.apache.catalina.valves.ErrorReportValve.invoke(Unknown Source)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(Unknown Source)
        at org.apache.catalina.core.StandardEngineValve.invoke(Unknown Source)
        at org.apache.catalina.connector.CoyoteAdapter.service(Unknown Source)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(Unknown Source)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(Unknown Source)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(Unknown Source)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.ProviderException: java.security.InvalidAlgorithmParameterException
        at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:146)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:704)
        at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:78)
        at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:714)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:278)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:849)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1035)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:721)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
        ... 88 more
Caused by: java.security.InvalidAlgorithmParameterException
        at sun.security.ec.ECKeyPairGenerator.generateECKeyPair(Native Method)
        at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:126)
        ... 98 more

20-Oct-2015 13:19:53.324 INFO [Handling POST /descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.3.78 : ajp-nio-8009-exec-7] jenkins.plugins.slack.StandardSlackService.publish Posting succeeded
```

**Comment by Leander1P** [comment]
We've started seeing this -- sporadically -- in build jobs, under `hudson.scm.SubversionSCM.calcChangeLog` (after checkout/update has finished).  So it's not slack-plugin.  Odd that slack-plugin seems to trigger it more reliably, though.

Looking at the sources, specifically http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/file/c084492f9e3d/src/share/native/sun/security/ec/ECC_JNI.cpp and http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/file/c084492f9e3d/src/share/native/sun/security/ec/impl/ecdecode.c , it looks like any allocation failures inside `EC_DecodeParam` before calling `EC_FillParams` to can cause `Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair` to return `SECFailure` ... but an unsupported OID or oid length can also cause `EC_FillParams` to do so.  Seems like if anything we may need to chase down what OID we're choosing.

**Comment by samrocketman** [comment]
This appears to happen for you during the HTTP POST - https://github.com/jenkinsci/slack-plugin/blob/slack-1.8/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L66

I see you're further along than I am in discovering the root cause of the issue.  Perhaps, you're missing Java Cryptography Extension Unlimited?

**Comment by Leander1P** [comment]
As far as I know, the Java Cryptography Extension Unlimited only applies to Sun; the OpenJDK stuff is theoretically already unlimited.

We appear to have "solved" the issue with a combination of moving our source control server from the Mozilla "Modern" cipher suite recommendation to the "Intermediate" cipher suite recommendation (also re-enabling TLSv1.0 -- see https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations ) and restarting tomcat-8.

I don't exactly understand how this fixed issues for slack (separate https server endpoint), unless it was actually the aforementioned allocation failures, or some kind of state poisoning in the `EC_*` stuff.  I don't see why it would carry any state between SSL connections to different servers, though.

I'm going to close this to get it out of the tracker, but will return here if we ever figure out root cause and post a comment -- just in case anyone else stumbles across it.

**Comment by samrocketman** [comment]
Thanks for the follow-up.
