### ISSUE TITLE
Notify Build Start with Perforce SCM Causes Failure

### ISSUE THREAD

**Issue by trippmartin** [jenkinsci/slack-plugin#175]
We are using the Perforce SCM and attempting to integrate Slack notifications into the build process. If we have "Notify Build Start" enabled, the following exception occurs and the build fails. I'm assuming the Perforce plugin does not implement the getAffectedFiles() method. 

It appears that a similar issue was corrected in the HipChat plugin by wrapping this code in a try/catch.
[HipChat Update](https://github.com/jlewallen/jenkins-hipchat-plugin/pull/60/files#r13417609)

FATAL: getAffectedFiles() is not implemented by this SCM
java.lang.UnsupportedOperationException: getAffectedFiles() is not implemented by this SCM
    at hudson.scm.ChangeLogSet$Entry.getAffectedFiles(ChangeLogSet.java:242)
    at jenkins.plugins.slack.ActiveNotifier.getChanges(ActiveNotifier.java:151)
    at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:86)
    at jenkins.plugins.slack.SlackNotifier$SlackJobProperty.prebuild(SlackNotifier.java:307)
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:837)
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:832)
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:828)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)

**Comment by stijnvanbever** [comment]
I have the same issue but we're using the Starteam SCM.
Is there a workaround without deselecting "Notify Build Start"?

**Comment by timja** [comment]
If this is still an issue then please reopen the issue, I would hope they have implemented the interface by now...
