### ISSUE TITLE
Upgrading to Slack 2.0 outbound webhooks breaks Jenkins [replicated]

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/slack-plugin#191]
This issue is going to be the center point for tracking the patching progress.  This issue supersedes the following issues:
* #188
* #189
* [JENKINS-33556][JENKINS-33556]

This issue was caused by the following merged change: #160

# Workaround (for Jenkins admins)

This section is for Jenkins admins who need a fix now.  This will entirely disable outbound webhooks in the Slack plugin 2.0.

1. Go to your `$JENKINS_HOME` and create a `init.groovy.d/` directory.
2. Download [this script to disable Slack outbound webhooks][disable-slack-webhooks] and copy it into `$JENKINS_HOME/init.groovy.d`.
3. Restart your Jenkins instance.

It should be back to normal and you'll be able to configure things again.  Slack outbound webhooks will always be disabled for the duration you have this script installed in `init.groovy.d/`.

# Problematic conditions

I was able to successfully reproduce the issue under the following conditions.

* Another plugin with webhooks configured (the bootstrap includes ghprb plugin i.e. github pull request builder plugin)
* Authentication enabled (recommend using the pre-installed github oauth plugin from the bootstrap).
* Only authenticated users get access (i.e. not anonymous).  I simply set the `authenticated` group to be administrators with the `Administer` permission.
* Upgrading from Slack 1.8.1 to 2.0.0.

# How to reproduce (for developers to patch)

1. [Bootstrap Jenkins with slack configured](https://github.com/samrocketman/jenkins-bootstrap-slack).  Simply clone the repository and execute `./slack_bootstrap.sh` on a Unix-like machine.  This will:
  * Pre-install an older version of Jenkins.
  * Pre-install and configure the slack plugin 1.8.1.
  * Configure some test jobs with slack configured.
  * Pre-install github-oauth and ghprb plugin.
2. Configure global security:
  1. Enable global security.
  2. Generate a [new GitHub OAuth Application](https://github.com/settings/applications/new).  With the following settings:
    * Application name: `Jenkins`
    * Homepage URL: `http://localhost:8080/`
    * Application description: `Jenkins testing.`
    * Authorization callback URL: `http://localhost:8080/securityRealm/finishLogin`
  3. Security Realm should be set to Github Authentication Plugin and configure it with the Client ID and Client Secret settings from your GitHub OAuth application.
  4. Under access control in the global security page configure *Authorization* and choose `Matrix-based security`.  Set the following settings:
    * `authenticated` group must have administer permissions.
    * `anonymous` group must not have any permissions.
3. Visit http://localhost:8080/manage and update Jenkins to latest edition.
4. Restart Jenkins after upgrade.
5. Visit http://localhost:8080/pluginManager/ and update all plugins (including Slack plugin 2.0) to latest editions.
6. Restart Jenkins after upgrade.

From this point, you should get a stack trace like in [JENKINS-33556][JENKINS-33556].  Following the above steps reproduces the issue every time.

Additional bootstrap commands:
* Restart the Jenkins instance with `./scripts/provision_jenkins.sh restart`
* Delete and clean up everying.  `./gradlew clean`
* Bootstrap everything again.  `./slack_bootstrap.sh`

[JENKINS-33556]: https://issues.jenkins-ci.org/browse/JENKINS-33556
[disable-slack-webhooks]: https://github.com/samrocketman/jenkins-script-console-scripts/blob/master/disable-slack-webhooks.groovy

**Comment by kmadel** [comment]
I understand the issue with #189 - but not clear how the webhook changes caused #188 
I couldn't reproduce #188 but did see #189

**Comment by samrocketman** [comment]
Re-opening since there's a report stating it's still not fixed.  I'll have to follow up with my own testing tomorrow.

**Comment by daniel-beck** [comment]
@samrocketman Why is the webhook URL even configurable in #160, rather than (maybe) having a checkbox for enable/disable? Seems unnecessary, and I've never seen a plugin do this.

**Comment by samrocketman** [comment]
@daniel-beck not sure, for the most part I've largely handed off this project to @kmadel as I don't do much development for this plugin.  Even when I did maintain it I didn't actually develop.  I only merged others' pull requests.  I wasn't really involved in the merge of #160 but when things broke I did provide a workaround to disable it.  I agree it should have an option to be disabled.

Side note, I handed it off because I don't/didn't actually use the slack plugin and I figure if someone is actually using it they'll be able to better support it.

**Comment by OwensCode** [comment]
I wasn't involved in the development of the feature but I was involved with the code review. I recommended that the URL be configurable so you could run it alongside other similar plugins without clashing, especially since it was originally listening on /webhook. A checkbox to enable/disable sounds like a good enhancement. It also works around another concern that I had, which is that it was enabled by default, even if you have no interest in the functionality and could consider it a security risk.

**Comment by netbe** [comment]
@OwensCode any idea how I can disable this once installed since jenkins is crashed, a quick fix could be to give the process to deactivate it if that's the problem + deactivate it by default for next release

**Comment by OwensCode** [comment]
@netbe There's a link to a script by @samrocketman at the top of this page, in the "Workaround (for Jenkins admins)" section.

**Comment by OwensCode** [comment]
Is this still an issue @samrocketman? Do we have any more information from people still being impacted by it after the fix was released? I would like to take a look at fixing it, if there is something to fix.

**Comment by samrocketman** [comment]
@OwensCode let me take a look this evening or weekend.  I'll follow up and try to be detailed if I can reproduce.

**Comment by mikz** [comment]
This was issue for me. Fresh installation of slack plugin on jenkins 2.1. And even though I set up the outgoing webhooks, the Global Tool Configuration crashed pointing to https://github.com/jenkinsci/slack-plugin/blob/ae8e6e351fa4633e0d494187333298eaa3b41904/src/main/java/jenkins/plugins/slack/webhook/WebhookEndpoint.java#L51.

The workaround worked and the page no longer crashes.

**Comment by pkkummermo** [comment]
I had Jenkins failing during startup with the same issues as above. My solution was the following:

1. Remove $JENKINS_HOME/plugins/slack
2. Restart Jenkins
3. Go to Manage Jenkins -> Manage Old Data -> Discard old data
4. Install Slack Plugin
5. Jenkins restart.

CAUTION: This will wipe your old Slack configurations, but I prioritized having the Slack integration up and running and took the time to redo the integrations.

**Comment by ElaineRichards** [comment]
My workaround is to move the jobs directory to "jobs.safe", restart jenkins, remove the generated empty jobs directory and move "jobs.safe" 

The side effect of this is that I've had to change my Perforce population option from "forced clean and sync" to "Auto cleanup".

**Comment by samrocketman** [comment]
@ElaineRichards see the workaround discussed in the description of this issue.

**Comment by SimonPNorra** [comment]
Please promote the solution of @pkkummermo from 13th of July. 

This did work for me as well.

Thanks @pkkummermo

**Comment by samrocketman** [comment]
@SimonPNorra 

>Please promote the solution of @pkkummermo from 13th of July.

>This did work for me as well.

>Thanks @pkkummermo

I updated the original post to reflect his solution as "Option 1".

**Comment by pedromartinez11** [comment]
Does 2.2 have the same problems?

On 2.1 I'm able to go into Jenkins, but I have to regularly restart it after getting the NullPointerException from the slack plugin.

**Comment by j796160836** [comment]
I installed lastest slack notification plugins (version 2.2) also encountered this error.
Apply **Option 2 Workaround** (see above)  and save my time, thanks.

**Comment by fengxx** [comment]
to workaround the issue, run the script on Jenkins script console 
```
import jenkins.plugins.slack.webhook.GlobalConfig;
import jenkins.plugins.slack.webhook.WebhookEndpoint;
def splackConfig=Jenkins.getActiveInstance().getDescriptor(GlobalConfig.class);
def slackWebHook=Jenkins.getActiveInstance().getExtensionList(WebhookEndpoint.class).get(0);
println splackConfig
println slackWebHook
println slackWebHook.@globalConfig
slackWebHook.@globalConfig=splackConfig
```
It will output something like
jenkins.plugins.slack.webhook.GlobalConfig@526ba2e2
jenkins.plugins.slack.webhook.WebhookEndpoint@15ab7a57
null
Result: jenkins.plugins.slack.webhook.GlobalConfig@526ba2e2

**Comment by boxymoron** [comment]
This is still happening on Jenkins ver. 2.114 + Slack Notification Plugin ver. 2.3
The fix from @fengxx worked for these versions.

**Comment by brandoncordell** [comment]
This is _still_ happening. Is this plugin abandoned? Is there another plugin I should use instead?

**Comment by hugespoon** [comment]
Can confirm that this issue still seems to be occurring (Jenkins 2.32.2 and Slack Plugin 2.3). 

Lots of the following in the logs:

`at jenkins.plugins.slack.webhook.WebhookEndpoint.getUrlName(WebhookEndpoint.java:51)
        at jenkins.model.Jenkins.getDynamic(Jenkins.java:3565)`

**Comment by Flightkick** [comment]
At the time of writing (plugin version 2.3) this is still an issue.
A reboot of the Jenkins instance will fix the NPE being thrown.

@Wadeck 's pull request appears to fix the issue but the fix has not yet been released: https://github.com/jenkinsci/slack-plugin/pull/403
