### ISSUE TITLE
Slack plugin 2.0 breaks Jenkins 1.647

### ISSUE THREAD

**Issue by cooniur** [jenkinsci/slack-plugin#196]
Jenkins Version: 1.647
Slack plugin version: 2.0

## Overview
After installing/upgrading to Slack plugin 2.0, it prevents Jenkins server from starting up with a NullPointerException.

I suspect that it could be a backward-compatibility issue with Slack plugin 2.0 as I would assume the Slack plugin 2.0 release would be for Jenkins 2.0 version. So I suppose the same issue would happen to all 1.xxx versions.

## How to reproduce?
1. Login into Jenkins server
2. Stop Jenkins server: `service jenkins stop`
3. Remove plugin folder: `cd /var/lib/jenkins && mv plugins plugins.origin`
4. Start Jenkins server: `service jenkins start`
5. Install Slack Plugin 2.0
6. Jenkins starts but loads a failure page with the following error message:

	![The Angry Jenkins Icon](https://avatars0.githubusercontent.com/u/10986514?v=3&s=100)

>

	A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.

	Stack trace

	java.lang.NullPointerException
		at java.util.TreeMap.put(TreeMap.java:563)
		at java.util.TreeSet.add(TreeSet.java:255)
		at jenkins.model.Jenkins.getUnprotectedRootActions(Jenkins.java:3916)
		at jenkins.model.Jenkins.getTarget(Jenkins.java:3885)
		at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:674)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
		at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
		at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
		at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
		at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
		at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:129)
		at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
		at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
		at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
		at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
		at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
		at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
		at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
		at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
		at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
		at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
		at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
		at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
		at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
		at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
		at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
		at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
		at org.eclipse.jetty.server.Server.handle(Server.java:370)
		at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
		at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
		at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
		at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
		at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
		at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
		at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
		at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
		at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

**Comment by samrocketman** [comment]
Duplicates #191.  Fixed in release 2.0.1 see #193.

**Comment by cooniur** [comment]
@samrocketman Thanks! BTW, how soon is the 2.0.1 going to be released to Jenkins plugin updates?

**Comment by shaneargo** [comment]
It is already in the update centre for me.

**Comment by cooniur** [comment]
Yes it is! (after click `Check Now` button)

Thanks, @shaneargo !

**Comment by samrocketman** [comment]
@cooniur generally, any release to Jenkins Artifactor takes roughly 8 hours to appear in the update center.  A good rule of thumb is to look at when it was released and just add 8 hrs to it.  One could always download it directly [from artifactory](https://repo.jenkins-ci.org/webapp/#/artifacts/browse/simple/search/quick/) by searching `slack-2.0.1`.
