### ISSUE TITLE
Slack plugin appears to be preventing webhook from working

### ISSUE THREAD

**Issue by keirlawson** [jenkinsci/slack-plugin#243]
I'm trying to use webhooks from gitlab to trigger builds, however whenever a webhook is hit I now get:

```
java.lang.NullPointerException at jenkins.plugins.slack.webhook.WebhookEndpoint.getUrlName(WebhookEndpoint.java:51) at jenkins.model.Jenkins.getUnprotectedRootActions(Jenkins.java:4342) at jenkins.model.Jenkins.getTarget(Jenkins.java:4311) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:674) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649) at org.kohsuke.stapler.Stapler.service(Stapler.java:238) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135) at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook$GitlabWebHookCrumbExclusion.process(GitLabWebHook.java:53) at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:58) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84) at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249) at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76) at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.eclipse.jetty.server.Server.handle(Server.java:499) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)
```

The build in question does not have slack notifications enabled.

I am using Jenkins 2.7.1

**Comment by lfberge** [comment]
The same happens for me with Jenkins 2.17.

**Comment by dpires** [comment]
Interesting, this was an issue when the outgoing-webhook was first merged. If you didn't set an endpoint, it would fail. However, a random uuid is now set by default.

I can't reproduce this on a fresh setup: (Jenkins 2.7.2, Slack Plugin: 2.0.1) I have tried a external webhook and it has worked.

Maybe this is an issue when upgrading the slack plugin and or upgrading jenkins.

**Comment by scholtzm** [comment]
Getting the same error. Also noticed these 2 fields which are not mentioned anywhere in the setup instructions. What is their purpose?

<img width="1060" alt="fields" src="https://cloud.githubusercontent.com/assets/2640934/17802010/e4176c70-65ed-11e6-8826-3c3ce5266eb3.png">

Slack integration itself only provides `token`.

**Comment by keirlawson** [comment]
For me the issue seems to have been resolved by restarting Jenkins

**Comment by scholtzm** [comment]
Restarting Jenkins again seems to have helped. Thanks for the tip.

**Comment by kmadel** [comment]
I became co-maintainer just as the PR for outgoing webhooks needed to be merged - so I am responsible for releasing it, but in retrospect it should have never been released without any documentation and configuration that is completely separate from the existing config. I feel like this functionality belongs in another plugin entirely.

**Comment by pres** [comment]
I just installed the plugin and it is working fine for me atm.
But I found the mentioned `Slack Webhook Settings` and I'm now trying to figure out what they are for. Is there some documentation anywhere?

**Comment by dpires** [comment]
@kmadel I agree that the webhook should be a separate plugin, it originally started as one, but was turned down. I kept the configuration separate as a way of avoiding confusion between the tokens. 

As far as documentation is concerned, all settings are documented, however at the time of creation I didn't (still might not) have access to the wiki.  If I have access I can add it. 

Also if you want to bring up the issue as per moving it to its own plugin, that works too as that was the original intent.

@pres documentation is available here: 
https://github.com/dpires/jenkins-slack-webhook-plugin

The webhook functionality if configured allows Jenkins to act as a simple slack bot that will respond to commands.

**Comment by timja** [comment]
Raised https://github.com/jenkinsci/slack-plugin/issues/441 for documentation
The restart isn't needed after version 2.4
