### ISSUE TITLE
Upgrading to 2.0.1 breaks jenkins 2.2

### ISSUE THREAD

**Issue by rodriguezsergio** [jenkinsci/slack-plugin#257]
I upgraded from 1.8.1 to 2.0.1 and it broke jenkins 2.2.

From the GUI

```
hudson.util.HudsonFailedToLoad: java.lang.AssertionError: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
    at hudson.WebAppMain$3.run(WebAppMain.java:240)
Caused by: java.lang.AssertionError: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
    at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1301)
    at hudson.model.JobProperty.getDescriptor(JobProperty.java:105)
    at hudson.model.JobProperty.getDescriptor(JobProperty.java:79)
    at hudson.model.Descriptor.toMap(Descriptor.java:982)
    at hudson.model.Job.getProperties(Job.java:558)
    at org.jenkinsci.plugins.envinject.migration.EnvInjectMigrationListener.onLoaded(EnvInjectMigrationListener.java:45)
    at jenkins.model.Jenkins.<init>(Jenkins.java:917)
    at hudson.model.Hudson.<init>(Hudson.java:85)
    at hudson.model.Hudson.<init>(Hudson.java:81)
    at hudson.WebAppMain$3.run(WebAppMain.java:226)
```

/var/log/jenkins/jenkins.log

```
INFO: Jenkins stopped
Oct 13, 2016 11:58:54 AM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (Jenkins initialization thread/15) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.AssertionError: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
        at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1301)
        at hudson.model.JobProperty.getDescriptor(JobProperty.java:105)
        at hudson.model.JobProperty.getDescriptor(JobProperty.java:79)
        at hudson.model.Descriptor.toMap(Descriptor.java:982)
        at hudson.model.Job.getProperties(Job.java:558)
        at org.jenkinsci.plugins.envinject.migration.EnvInjectMigrationListener.onLoaded(EnvInjectMigrationListener.java:45)
        at jenkins.model.Jenkins.<init>(Jenkins.java:917)
        at hudson.model.Hudson.<init>(Hudson.java:85)
        at hudson.model.Hudson.<init>(Hudson.java:81)
        at hudson.WebAppMain$3.run(WebAppMain.java:226)

Oct 13, 2016 11:58:58 AM javax.jmdns.impl.DNSStatefulObject$DefaultImplementation waitForAnnounced
```

**Comment by rodriguezsergio** [comment]
The issue is still present.

```
hudson.util.HudsonFailedToLoad: java.lang.AssertionError: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
	at hudson.WebAppMain$3.run(WebAppMain.java:240)
Caused by: java.lang.AssertionError: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
	at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1301)
	at hudson.model.JobProperty.getDescriptor(JobProperty.java:105)
	at hudson.model.JobProperty.getDescriptor(JobProperty.java:79)
	at hudson.model.Descriptor.toMap(Descriptor.java:982)
	at hudson.model.Job.getProperties(Job.java:558)
	at org.jenkinsci.plugins.envinject.migration.EnvInjectMigrationListener.onLoaded(EnvInjectMigrationListener.java:45)
	at jenkins.model.Jenkins.<init>(Jenkins.java:917)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:226)
```

**Comment by rodriguezsergio** [comment]
@ydubreuil @kmadel when is the fix going to be available?

**Comment by ydubreuil** [comment]
Um, that's weird, patch https://github.com/jenkinsci/slack-plugin/commit/910b473b3e4b6a9f697528a09d16dade4691be9a was working for me. Do you have a `config.xml` which exhibits the issue?

**Comment by rodriguezsergio** [comment]
@ydubreuil where should I send the contents of `config.xml` to?

Also, for what it's worth, I'm running Jenkins 2.36 and Env Inject 1.93.1 now.

**Comment by rodriguezsergio** [comment]
I upgraded some other plugins and tried to install this plugin again, but now get the following error

```
hudson.util.HudsonFailedToLoad: java.lang.AssertionError: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
	at hudson.WebAppMain$3.run(WebAppMain.java:245)
Caused by: java.lang.AssertionError: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
	at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1533)
	at hudson.model.JobProperty.getDescriptor(JobProperty.java:105)
	at hudson.model.JobProperty.getDescriptor(JobProperty.java:79)
	at hudson.model.Descriptor.toMap(Descriptor.java:989)
	at hudson.model.Job.getProperties(Job.java:554)
	at org.jenkinsci.plugins.envinject.migration.EnvInjectMigrationListener.onLoaded(EnvInjectMigrationListener.java:47)
	at jenkins.model.Jenkins.<init>(Jenkins.java:995)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:231)
```

**Comment by samrocketman** [comment]
gist?

**Comment by rodriguezsergio** [comment]
https://gist.github.com/rodriguezsergio/3a9c797a77dda265a8523915de2e76de

**Comment by rodriguezsergio** [comment]
Is that helpful at all? Would a list of active plugins and their versions be useful, too?

**Comment by samrocketman** [comment]
I reviewed it.  It's hard for me to say if it's useful.  Not because you did anything wrong.  But because I'm having a hard time imagining the conditions in which this issue pops up.  It definitely continues to pop up during people's migrations.
