### ISSUE TITLE
NullPointerException with pipeline in fresh Jenkins installation

### ISSUE THREAD

**Issue by StephenKing** [jenkinsci/slack-plugin#278]
When using the `slackSend` step with the pipeline plugins in an empty Jenkins configuration, a `NullPointerException` is thrown, even if `failOnError: false` is set.

After saving the global Jenkins configuration once, the pipeline runs successfully.

````
java.lang.NullPointerException
	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:46)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.getSlackService(SlackSendStep.java:193)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:181)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:149)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
````

Go to [StandardSlackService.java:46](https://github.com/jenkinsci/slack-plugin/blob/8b96c38d5577eb70aee6d01c67ef3ffa4bf396f5/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L46).

**Comment by timja** [comment]
should be fixed in 2.4 otherwise will need a new stacktrace as line numbers have changed a lot
