### ISSUE TITLE
the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by minjimwu** [jenkinsci/slack-plugin#314]
I encounter this issue this week, it was working fine before.
I use Jenkins 2.51, and my Java is update to 8 version 131

the error message like this:

Error posting to Slack
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(Unknown Source)
	at java.security.cert.PKIXParameters.<init>(Unknown Source)
	at java.security.cert.PKIXBuilderParameters.<init>(Unknown Source)
Caused: java.lang.RuntimeException: Unexpected error
	at sun.security.validator.PKIXValidator.<init>(Unknown Source)
	at sun.security.validator.Validator.getInstance(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)

**Comment by ebirn** [comment]
Had a similar thing on LTS, it (trustAnchors error) was fixed for me when updating to Jenkins ver. 2.46.2.

However still did not work to send message, although logs said all ok:
Apr 27, 2017 9:23:54 AM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting succeeded

I was using the credential ID for slack integration token. It was resolved after using a dummy value for the integration token in the config form and selecting the credential id for the token (which overrides the cleartext token according to docs).

**Comment by minjimwu** [comment]
I do nothing, but it's back to normal today automatically. lol

**Comment by minjimwu** [comment]
after a week, it's still work well.

**Comment by hhimanshuvyass** [comment]
for me it got resolved just by upgrading "Email extension plugin" to latest version (2.61).
