### ISSUE TITLE
POST error made the jenkins job status error

### ISSUE THREAD

**Issue by suifengcnn** [jenkinsci/slack-plugin#326]
i got in this error amazing...
my jenkins would hung on the jos queue...it can not get the job status and finish the job.

test connect shows OK,but sometime the jenkins jobs went into hung...

the jenkins log show:
19-Jun-2017 10:58:00.421 INFO [SCM polling for hudson.model.FreeStyleProject@1ef9e8f[bfront-dev]] hudson.triggers.SCMTrigger$Runner.run SCM changes detected in bfront-dev. Triggering  #21
19-Jun-2017 10:58:09.209 INFO [Executor #2 for master : executing bfront-dev #21] jenkins.plugins.slack.SlackNotifier.prebuild Invoking Started...
19-Jun-2017 10:58:09.209 INFO [Executor #2 for master : executing bfront-dev #21] jenkins.plugins.slack.ActiveNotifier.getChanges Entry hudson.scm.SubversionChangeLogSet$LogEntry@aee5b53c
19-Jun-2017 10:58:09.209 INFO [Executor #2 for master : executing bfront-dev #21] jenkins.plugins.slack.ActiveNotifier.getChanges Entry hudson.scm.SubversionChangeLogSet$LogEntry@5915e4a0
19-Jun-2017 10:58:09.210 INFO [Executor #2 for master : executing bfront-dev #21] jenkins.plugins.slack.ActiveNotifier.getChanges Entry hudson.scm.SubversionChangeLogSet$LogEntry@1f47f2de
19-Jun-2017 10:58:09.210 INFO [Executor #2 for master : executing bfront-dev #21] jenkins.plugins.slack.ActiveNotifier.getChanges Entry hudson.scm.SubversionChangeLogSet$LogEntry@d972ace5
19-Jun-2017 10:58:52.351 WARNING [Executor #2 for master : executing bfront-dev #21] jenkins.plugins.slack.StandardSlackService.publish Error posting to Slack
 org.apache.http.NoHttpResponseException: The target server failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
        at com.sun.proxy.$Proxy64.receiveResponseHeader(Unknown Source)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:126)
        at jenkins.plugins.slack.ActiveNotifier.notifyStart(ActiveNotifier.java:95)
        at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:83)a
        at jenkins.plugins.slack.SlackNotifier.prebuild(SlackNotifier.java:345)
        at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:833)
        at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:828)
        at hudson.model.Build$BuildExecution.doRun(Build.java:145)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
        at hudson.model.Run.execute(Run.java:1728)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:405)

19-Jun-2017 10:59:14.838 INFO [Executor #2 for master : executing bfront-dev #21] hudson.model.Run.execute bfront-dev #21 main build action completed: SUCCESS
19-Jun-2017 11:17:31.677 WARNING [Handling POST /jenkins/view/DEVBUILD/ajaxExecutors from 192.168.0.9 : http-nio-9090-exec-4] hudson.security.csrf.CrumbFilter.doFilter Found invalid crumb 11cd5278c0fbeeb06c28376e3b073a34.  Will check remaining parameters for a valid one...
19-Jun-2017 11:17:31.677 WARNING [Handling POST /jenkins/view/DEVBUILD/ajaxBuildQueue from 192.168.0.9 : http-nio-9090-exec-9] hudson.security.csrf.CrumbFilter.doFilter Found invalid crumb 11cd5278c0fbeeb06c28376e3b073a34.  Will check remaining parameters for a valid one...
19-Jun-2017 11:17:31.678 WARNING [Handling POST /jenkins/view/DEVBUILD/ajaxExecutors from 192.168.0.9 : http-nio-9090-exec-4] hudson.security.csrf.CrumbFilter.doFilter No valid crumb was included in request for /jenkins/view/DEVBUILD/ajaxExecutors. Returning 403.
19-Jun-2017 11:17:31.679 WARNING [Handling POST /jenkins/view/DEVBUILD/ajaxBuildQueue from 192.168.0.9 : http-nio-9090-exec-9] hudson.security.csrf.CrumbFilter.doFilter No valid crumb was included in request for /jenkins/view/DEVBUILD/ajaxBuildQueue. Returning 403.
19-Jun-2017 11:49:31.631 INFO [Handling POST /jenkins/descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection from 192.168.0.107 : http-nio-9090-exec-1] jenkins.plugins.slack.StandardSlackService.publish Posting succeeded
~

![2017-06-19_115141](https://user-images.githubusercontent.com/12423374/27269125-c4f7589e-54e6-11e7-8523-1fa8cd667b78.png)
![2017-06-19_115515](https://user-images.githubusercontent.com/12423374/27269126-c5101b9a-54e6-11e7-9524-5556bb20050f.png)

**Comment by suifengcnn** [comment]
the job next run will be hang too,i need to restart jenkins manually

**Comment by timja** [comment]
re-open if you're still having problems...
