### ISSUE TITLE
java.lang.NumberFormatException: For input string / can't parse argument number

### ISSUE THREAD

**Issue by samodadela** [jenkinsci/slack-plugin#365]
Hi, 

I'm getting the stacktrace below each time a build is started by the (parametrized) schedule... What's weird is that if I start the build manually the error does not happen... Running on macosx. Jenkins is fully updated, slack plugin is version 2.3. CR_SOURCE is a choice parameter, builds are triggered by parametrized schedule:

```
# once every hour at 15 minutes past the hour starting at 6:15 AM and finishing at 22:45 PM every day
15 6-22/4 * * * % CR_SOURCE=store;CR_MODE=delta
45 6-22/4 * * * % CR_SOURCE=devel;CR_MODE=delta
15 11,23 * * *       % CR_SOURCE=store;CR_MODE=full
45 11,23 * * *       % CR_SOURCE=devel;CR_MODE=full
```

For slack plugin I have checked all the non-advanced options (Notify Build Start to Botify Back to Normal)... and the only advanced option is to Include Custom Message, set to "source: $CR_SOURCE mode: $CR_MODE archive: http://10.95.55.11/crashes/$CR_SOURCE"

The 'test send' button works. Also starting the build manually does not produce the error.

I tried uninstalling/reinstalling slack plugin, but it didn't help. Why is it trying to parse this? How can I troubleshoot this further?

```
 > git rev-list --no-walk 09f855cd15e2443a5a3d28715a162d9f24edbf54 # timeout=10
No emails were triggered.
FATAL: can't parse argument number: CR_SOURCE=store
java.lang.NumberFormatException: For input string: "CR_SOURCE=store"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1427)
Caused: java.lang.IllegalArgumentException: can't parse argument number: CR_SOURCE=store
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1429)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at java.text.MessageFormat.<init>(MessageFormat.java:362)
	at java.text.MessageFormat.format(MessageFormat.java:840)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.escape(ActiveNotifier.java:490)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.append(ActiveNotifier.java:369)
	at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:70)
	at jenkins.plugins.slack.SlackNotifier.prebuild(SlackNotifier.java:345)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:798)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:793)
	at hudson.model.Build$BuildExecution.doRun(Build.java:145)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Email was triggered for: Failure - Any
```

**Comment by samodadela** [comment]
Thinking about it... is it maybe trying to parse the cron schedule? Note that I'm using the parametrized scheduler. The syntax is the same as for the normal scheduler, but parameters can be added in the end (% VAR1=val1;VAR2=val2)

**Comment by 2toginc** [comment]
I've got a similar issue to @samodadela, with the slack plugin running with the parameterized scheduler plugin.

A workaround for me was to uncheck "notify build start" in the slack plugin (leaving checked "notify failure" and "notify success"), but this is obviously not optimal.  As @samodadela suspects, it's probably due to parsing the "cron" entry in the slack build start hook.

I hope this helps the plugin developers solve the issue.

**Comment by jsoref** [comment]
Offhand, it looks like https://github.com/jenkinsci/slack-plugin/blob/e90f7f4d3c31fa9d50e0e2154bbe2a91686d1d69/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L473 is bad.

Using:
http://www.javarepl.com/term.html
```java
java> import java.io.IOException;
Imported java.io.IOException
java> import java.text.MessageFormat;
Imported java.text.MessageFormat
java> import java.util.ArrayList;
Imported java.util.ArrayList
java> import java.util.HashSet;
Imported java.util.HashSet
java> import java.util.LinkedList;
Imported java.util.LinkedList
java> import java.util.List;
Imported java.util.List
java> import java.util.Set;
Imported java.util.Set
java> import java.util.logging.Logger;
Imported java.util.logging.Logger
java> import java.util.regex.Matcher;
Imported java.util.regex.Matcher
java> import java.util.regex.Pattern;
Imported java.util.regex.Pattern
java> Pattern aTag = Pattern.compile("(?i)<a([^>]+)>(.+?)</a>");
java.util.regex.Pattern aTag = (?i)<a([^>]+)>(.+?)</a>
java> Pattern href = Pattern.compile("\\s*(?i)href\\s*=\\s*(\"([^\"]*\")|'[^']*'|([^'\">\\s]+))");
java.util.regex.Pattern href = \s*(?i)href\s*=\s*("([^"]*")|'[^']*'|([^'">\s]+))
java> import static java.util.logging.Level.INFO;
Imported static
java> import static java.util.logging.Level.SEVERE;
Imported static
java> String[] extractReplaceLinks(Matcher aTag, StringBuffer sb) {
            int size = 0;
            List<String> links = new ArrayList<String>();
            while (aTag.find()) {
                Matcher url = href.matcher(aTag.group(1));
                if (url.find()) {
                    aTag.appendReplacement(sb,String.format("{%s}", size++));
                    links.add(String.format("<%s|%s>", url.group(1).replaceAll("\"", ""), aTag.group(2)));
                }
            }
            aTag.appendTail(sb);
            return links.toArray(new String[size]);
        }
Created method java.lang.String[] extractReplaceLinks(java.util.regex.Matcher, java.lang.StringBuffer)
java> StringBuffer pattern = new StringBuffer();
java.lang.StringBuffer pattern = 
java> String string = "hello world";
java.lang.String string = "hello world"
java> String[] links = extractReplaceLinks(aTag.matcher(string), pattern);
java.lang.String[] links = []
java> links
java.lang.String[] links = []
java> links.length
java.lang.Integer res5 = 0
java> pattern
java.lang.StringBuffer pattern = hello world
java> String escapeCharacters(String string) {
            string = string.replace("&", "&");
            string = string.replace("<", "<");
            string = string.replace(">", ">");
            return string;
        }
Created method java.lang.String escapeCharacters(java.lang.String)
java> String string = "hello <a href=\"http://test\">case</a> world";
java.lang.String string = "hello <a href="http://test">case</a> world"
java> pattern = new StringBuffer();
java.lang.StringBuffer pattern = 
java> links = extractReplaceLinks(aTag.matcher(string), pattern);
java.lang.String[] links = ["<http://test|case>"]
java> pattern
java.lang.StringBuffer pattern = hello {0} world
java> MessageFormat.format(escapeCharacters(pattern.toString()), links);
java.lang.String res6 = "hello <http://test|case> world"
java> pattern = new StringBuffer();
java.lang.StringBuffer pattern = 
java> string = "hello <a href=\"http://test?foo={x}\">case</a> world";
java.lang.String string = "hello <a href="http://test?foo={x}">case</a> world"
java> links = extractReplaceLinks(aTag.matcher(string), pattern);
java.lang.String[] links = ["<http://test?foo={x}|case>"]
java> MessageFormat.format(escapeCharacters(pattern.toString()), links);
java.lang.String res7 = "hello <http://test?foo={x}|case> world"
java> pattern = new StringBuffer();
java.lang.StringBuffer pattern = 
java> string = "hello{x} <a href=\"http://test\">case</a> world";
java.lang.String string = "hello{x} <a href="http://test">case</a> world"
java> links = extractReplaceLinks(aTag.matcher(string), pattern);
java.lang.String[] links = ["<http://test|case>"]
java> MessageFormat.format(escapeCharacters(pattern.toString()), links);
java.lang.IllegalArgumentException: can't parse argument number: x
```

**Comment by pavelpp** [comment]
When is this going to be fixed?

**Comment by timja** [comment]
Released in 2.4

**Comment by KaminerD** [comment]
Hi i'm still experiencing this issue in 2.15 when using the Parameterized Scheduler.
`> git rev-list --no-walk 4299e6d91aecfbe9da8788292dab0eec4d419a0a # timeout=10
FATAL: can't parse argument number: GIT_BRANCH=feature/OO-5347/anomalies-end-to-end
java.lang.NumberFormatException: For input string: "GIT_BRANCH=feature/OO-5347/anomalies-end-to-end"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1427)
Caused: java.lang.IllegalArgumentException: can't parse argument number: GIT_BRANCH=feature/OO-5347/anomalies-end-to-end
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1429)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at java.text.MessageFormat.<init>(MessageFormat.java:362)
	at java.text.MessageFormat.format(MessageFormat.java:840)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.escape(ActiveNotifier.java:545)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.append(ActiveNotifier.java:382)
	at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:69)
	at jenkins.plugins.slack.SlackNotifier.prebuild(SlackNotifier.java:459)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:798)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:793)
	at hudson.model.Build$BuildExecution.doRun(Build.java:145)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)`
Thanks

**Comment by timja** [comment]
Needs a similar to PR: https://github.com/jenkinsci/slack-plugin/pull/374/files
Along with tests which the previous change was missing

**Comment by timja** [comment]
Can you open a new issue please

**Comment by KaminerD** [comment]
done thx :)
https://github.com/jenkinsci/slack-plugin/issues/509
