### ISSUE TITLE
slack plugin bootstrapping - fails after upgrade 2.3 -> 2.4

### ISSUE THREAD

**Issue by Constantin07** [jenkinsci/slack-plugin#427]
After upgrading slack plugin from 2.3 to 2.4 the bootstrapping code stopped working in Jenkins 2.152:

Actual code:
```groovy
import com.cloudbees.jenkins.plugins.sshcredentials.impl.*
import com.cloudbees.plugins.credentials.*
import com.cloudbees.plugins.credentials.common.*
import com.cloudbees.plugins.credentials.domains.Domain
import com.cloudbees.plugins.credentials.impl.*
import hudson.util.Secret
import java.nio.file.Files
import jenkins.model.Jenkins
import net.sf.json.JSONObject
import org.jenkinsci.plugins.plaincredentials.impl.*

// parameters
def slackCredentialParameters = [
  description:  'Slack Jenkins integration token',
  id:           'slack-token',
  secret:       '****************'
]

def slackParameters = [
  slackBaseUrl:             'https:/********************/services/hooks/jenkins-ci/',
  slackBotUser:             'true',
  slackBuildServerUrl:      'https://jenkins.**************.com/',
  slackRoom:                '#slack_channel',
  slackSendAs:              'jenkins',
  slackTeamDomain:          'Company',
  slackToken:               '',
  slackTokenCredentialId:   'slack-token'
]

// get Jenkins instance
Jenkins jenkins = Jenkins.getInstance()

// get credentials domain
def domain = Domain.global()

// get credentials store
def store = jenkins.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')[0].getStore()

// get Slack plugin
def slack = jenkins.getExtensionList(jenkins.plugins.slack.SlackNotifier.DescriptorImpl.class)[0]

// define secret
def secretText = new StringCredentialsImpl(
  CredentialsScope.GLOBAL,
  slackCredentialParameters.id,
  slackCredentialParameters.description,
  Secret.fromString(slackCredentialParameters.secret)
)

// define form and request
JSONObject formData = ['slack': ['tokenCredentialId': 'slack-token']] as JSONObject
def request = [getParameter: { name -> slackParameters[name] }] as org.kohsuke.stapler.StaplerRequest

// add credential to Jenkins credentials store
store.addCredentials(domain, secretText)

// add Slack configuration to Jenkins
slack.configure(request, formData)

// save to disk
slack.save()
jenkins.save()
```

The issue appears to be in this line:
```
slack.configure(request, formData)
```

I'm getting the following exception:
```
jenkins_master    | WARNING: Failed to run script file:/var/lib/jenkins/init.groovy.d/slack-integration.groovy
jenkins_master    | java.lang.UnsupportedOperationException
jenkins_master    | 	at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:52)
jenkins_master    | 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
jenkins_master    | 	at com.sun.proxy.$Proxy66.bindJSON(Unknown Source)
jenkins_master    | 	at jenkins.plugins.slack.SlackNotifier$DescriptorImpl.configure(SlackNotifier.java:492)
jenkins_master    | 	at jenkins.plugins.slack.SlackNotifier$DescriptorImpl$configure.call(Unknown Source)
jenkins_master    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
jenkins_master    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
jenkins_master    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
jenkins_master    | 	at 12-slack-integration.run(12-slack-integration.groovy:58)
jenkins_master    | 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
jenkins_master    | 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
jenkins_master    | 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
jenkins_master    | 	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
jenkins_master    | 	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
jenkins_master    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_master    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_master    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_master    | 	at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_master    | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins_master    | 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins_master    | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins_master    | 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
jenkins_master    | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins_master    | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_master    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_master    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_master    | 	at java.lang.Thread.run(Thread.java:748)
```

I'm not a Java developer, could someone help with this issue ?
PS: I cannot figure out from the above exception what is the problem ...

**Comment by Constantin07** [comment]
Thanks @timja for getting back. I've removed all slack prefixes as you suggested:

```groovy
def slackParameters = [
  botUser:             'true',
  room:                '#slack_channel'
  sendAs:              'jenkins',
  teamDomain:          'Company',
  tokenCredentialId:   'slack-token'
]
```
but it still fails:
```
jenkins_master    | WARNING: Failed to run script file:/var/lib/jenkins/init.groovy.d/slack-integration.groovy
jenkins_master    | java.lang.UnsupportedOperationException
jenkins_master    | 	at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:52)
jenkins_master    | 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
jenkins_master    | 	at com.sun.proxy.$Proxy67.bindJSON(Unknown Source)
jenkins_master    | 	at jenkins.plugins.slack.SlackNotifier$DescriptorImpl.configure(SlackNotifier.java:492)
jenkins_master    | 	at jenkins.plugins.slack.SlackNotifier$DescriptorImpl$configure.call(Unknown Source)
jenkins_master    | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
jenkins_master    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
jenkins_master    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
jenkins_master    | 	at 12-slack-integration.run(12-slack-integration.groovy:58)
jenkins_master    | 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
jenkins_master    | 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
jenkins_master    | 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
jenkins_master    | 	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
jenkins_master    | 	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
jenkins_master    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_master    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_master    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_master    | 	at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_master    | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins_master    | 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins_master    | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins_master    | 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
jenkins_master    | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins_master    | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_master    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_master    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_master    | 	at java.lang.Thread.run(Thread.java:748)
```

PS: I cannot use configuration as code now as I'm currently using Groovy scripts to do Global Config in Jenkins and I don't want to break anything.

**Comment by timja** [comment]
I'll test it out tomorrow...

**Comment by Constantin07** [comment]
Much appreciated @timja.

**Comment by timja** [comment]
@Constantin07 This will work for you:
```
import com.cloudbees.plugins.credentials.domains.Domain
import org.jenkinsci.plugins.plaincredentials.impl.*
import hudson.util.Secret
import com.cloudbees.plugins.credentials.CredentialsScope

def jenkins = Jenkins.getInstance()

def domain = Domain.global()
def store = jenkins.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')[0].getStore()

def slackCredentialParameters = [
  description:  'Slack Jenkins integration token',
  id:           'slack-token',
  secret:       '****************'
]

def secretText = new StringCredentialsImpl(
  CredentialsScope.GLOBAL,
  slackCredentialParameters.id,
  slackCredentialParameters.description,
  Secret.fromString(slackCredentialParameters.secret)
)
  
store.addCredentials(domain, secretText)

def slack = jenkins.getDescriptorByType(jenkins.plugins.slack.SlackNotifier.DescriptorImpl.class)
// slack.setBaseUrl - only needed for slack compatible applications e.g. Mattermost
slack.setTeamDomain('your-domain')
slack.setTokenCredentialId(slackCredentialParameters.id)
slack.setBotUser(false )
slack.setRoom('#general')

slack.save()
jenkins.save()

```

**Comment by Constantin07** [comment]
Thank you very much @timja. It worked.
PS: I had to add `import jenkins.model.Jenkins` to avoid exception.

**Comment by timja** [comment]
Right, I was using the script console which implicitly imports that for you, 
I've updated in case its useful for others.

Will leave it here for now, if more people coming looking for this I'll add it to the README

**Comment by Constantin07** [comment]
Once again, Many thanks @timja.
