### ISSUE TITLE
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

### ISSUE THREAD

**Issue by gudlyf** [jenkinsci/slack-plugin#438]
Jenkins: 2.155
Slack Plugin: 2.7

Code in Jenkinsfile:

`pipeline {
    agent { any }
       stages {
         stage('slack test') {
            steps {
              slackSend (message: "test")
            }
         }
       }
}`

More of the error:

`org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at jenkins.plugins.slack.workflow.SlackResponse.<init>(SlackResponse.java:15)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:272)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:198)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE`

The message does appear in Slack, but the build sees the resulting error from the plugin as a failure. Plugin works fine in Freestyle project.

**Comment by gudlyf** [comment]
FYI, I downgraded to 2.6 and this works fine.

**Comment by timja** [comment]
what's setup in your global configuration?
@steven-foster fyi

**Comment by timja** [comment]
It's this change:
https://github.com/jenkinsci/slack-plugin/pull/429

If its a bot user it expects a response, if its not a bot user it should just return null and not even try parse it

**Comment by gudlyf** [comment]
![configure_system__jenkins_](https://user-images.githubusercontent.com/422893/50012621-1d30a900-ff8d-11e8-91cb-fe5acaa5dac9.png)

**Comment by steven-foster** [comment]
I was able to reproduce by using the regular Slack Jenkins App token along with a Base URL and Bot User.
Apparently base URL + bot user do not work together.

To avoid this for now either, un-check Is Bot User or remove the base URL and switch to a Bot User integration token

**Comment by timja** [comment]
@steven-foster @gudlyf could you have a look at https://github.com/jenkinsci/slack-plugin/pull/439 please?

It appears that your config is invalid, but it would be easier for the plugin to handle it I think...
