### ISSUE TITLE
custom message missing from build start

### ISSUE THREAD

**Issue by purduemike** [jenkinsci/slack-plugin#440]
Since upgrading from 2.3 the behavior for the build start custom message in slack have changed.  From 2.3 and prior, the build start message would include the custom message.  But now on version 2.8, the build start message no longer includes the custom message.  

Can you add it back?  

Having the custom message in the build start is important b/c it provides details about the build, which could take a long time to complete.

Here is how it looked for <=2.3
<img width="502" alt="screen shot 2018-12-15 at 11 38 01 am" src="https://user-images.githubusercontent.com/3812871/50046844-1d00de00-005f-11e9-92f9-d68a1053c1a9.png">

Here is how it looks for 2.8
<img width="493" alt="screen shot 2018-12-15 at 11 37 40 am" src="https://user-images.githubusercontent.com/3812871/50046845-1d00de00-005f-11e9-8213-aaa1b293617b.png">

**Comment by purduemike** [comment]
@timja I'm not sure how to get the config.xml, but I've included a screenshot of my slack post build action.  

Also, I've tried to resave, modify the custom message, uncheck/recheck the Notify on build start.  None of these worked.

<img width="951" alt="screen shot 2018-12-15 at 12 39 14 pm" src="https://user-images.githubusercontent.com/3812871/50047259-c4354380-0066-11e9-9a42-f93a567a1a70.png">

**Comment by timja** [comment]
Ok, I'll try reproduce and take a look

**Comment by timja** [comment]
It works for me  @purduemike 
![image](https://user-images.githubusercontent.com/21194782/50047351-2b74e700-00ab-11e9-8e23-e3a1c1a7c06c.png)

![image](https://user-images.githubusercontent.com/21194782/50047354-37f93f80-00ab-11e9-8b45-0c45cf848bc0.png)

going to need the config.xml from the jenkin's job

e.g. mine is:
jobs/blahh/config.xml
```
  <publishers>
    <jenkins.plugins.slack.SlackNotifier plugin="slack@2.9-SNAPSHOT">
      <baseUrl></baseUrl>
      <teamDomain></teamDomain>
      <tokenCredentialId></tokenCredentialId>
      <botUser>false</botUser>
      <room></room>
      <startNotification>true</startNotification>
      <notifySuccess>false</notifySuccess>
      <notifyAborted>false</notifyAborted>
      <notifyNotBuilt>false</notifyNotBuilt>
      <notifyUnstable>false</notifyUnstable>
      <notifyRegression>false</notifyRegression>
      <notifyFailure>false</notifyFailure>
      <notifyBackToNormal>false</notifyBackToNormal>
      <notifyRepeatedFailure>false</notifyRepeatedFailure>
      <includeTestSummary>false</includeTestSummary>
      <includeFailedTests>false</includeFailedTests>
      <commitInfoChoice>NONE</commitInfoChoice>
      <includeCustomMessage>true</includeCustomMessage>
      <customMessage>what&apos;s up</customMessage>
    </jenkins.plugins.slack.SlackNotifier>
  </publishers>
```

**Comment by purduemike** [comment]
@timja Here it is.

```
<publishers>
    <jenkins.plugins.slack.SlackNotifier plugin="slack@2.8">
      <baseUrl></baseUrl>
      <teamDomain></teamDomain>
      <tokenCredentialId></tokenCredentialId>
      <botUser>false</botUser>
      <room></room>
      <startNotification>true</startNotification>
      <notifySuccess>true</notifySuccess>
      <notifyAborted>true</notifyAborted>
      <notifyNotBuilt>true</notifyNotBuilt>
      <notifyUnstable>true</notifyUnstable>
      <notifyRegression>true</notifyRegression>
      <notifyFailure>true</notifyFailure>
      <notifyBackToNormal>true</notifyBackToNormal>
      <notifyRepeatedFailure>true</notifyRepeatedFailure>
      <includeTestSummary>false</includeTestSummary>
      <includeFailedTests>false</includeFailedTests>
      <commitInfoChoice>NONE</commitInfoChoice>
      <includeCustomMessage>true</includeCustomMessage>
      <customMessage>BUILD_USER: @$BUILD_USER_ID
ENV: $ENV
SERVICE: $SERVICE
BRANCH: $BRANCH
BUILD: $BUILD
OMIT_VERIFY_BRANCH_BUILD: $OMIT_VERIFY_BRANCH_BUILD</customMessage>
    </jenkins.plugins.slack.SlackNotifier>
  </publishers>
```

Maybe you can include a carriage return in your custom message.

**Comment by timja** [comment]
![image](https://user-images.githubusercontent.com/21194782/50047468-c8388400-00ad-11e9-8ba5-92aaae6e0ce2.png)

I copy pasted your example and i had a stacktrace in my jenkins stdout logs with:
`MacroEvaluationException: Unrecognized macro 'BUILD_USER_ID' in 'BUILD_USER: @$BUILD_USER_ID`

maybe check your jenkins logs?

**Comment by purduemike** [comment]
@timja I've confirmed that this only happens when you include a variable in your custom message.  So try replacing your `hi` text with some variable.

**Comment by timja** [comment]
have you checked your jenkins stdout logs?

**Comment by timja** [comment]
It was probably this PR:
https://github.com/jenkinsci/slack-plugin/pull/401

judging from my stacktrace...

**Comment by purduemike** [comment]
@timja Here is the log with stack trace.

```
Dec 15, 2018 9:29:14 PM jenkins.plugins.slack.SlackNotifier prebuild
INFO: Performing start notifications
Dec 15, 2018 9:29:14 PM jenkins.plugins.slack.ActiveNotifier$MessageBuilder appendCustomMessage
SEVERE: Unrecognized macro 'BUILD_USER' in 'BUILD_USER: @$BUILD_USER
ENV: REDACTED
SERVICE: REDACTED
BRANCH: REDACTED
BUILD: REDACTED
OMIT_VERIFY_BRANCH_BUILD: false'
org.jenkinsci.plugins.tokenmacro.MacroEvaluationException: Unrecognized macro 'BUILD_USER' in 'BUILD_USER: @$BUILD_USER
ENV: REDACTED
SERVICE: REDACTED
BRANCH: REDACTED
BUILD: REDACTED
OMIT_VERIFY_BRANCH_BUILD: false'
	at org.jenkinsci.plugins.tokenmacro.Parser.processToken(Parser.java:326)
	at org.jenkinsci.plugins.tokenmacro.Action$KiHW1UeqOdqAwZul.run(Unknown Source)
	at org.parboiled.matchers.ActionMatcher.match(ActionMatcher.java:96)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.FirstOfMatcher.match(FirstOfMatcher.java:41)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.FirstOfMatcher.match(FirstOfMatcher.java:41)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.ZeroOrMoreMatcher.match(ZeroOrMoreMatcher.java:39)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.parserunners.BasicParseRunner.run(BasicParseRunner.java:72)
	at org.parboiled.parserunners.ReportingParseRunner.runBasicMatch(ReportingParseRunner.java:86)
	at org.parboiled.parserunners.ReportingParseRunner.run(ReportingParseRunner.java:66)
	at org.parboiled.parserunners.AbstractParseRunner.run(AbstractParseRunner.java:81)
	at org.parboiled.parserunners.AbstractParseRunner.run(AbstractParseRunner.java:76)
	at org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:68)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expand(TokenMacro.java:204)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:234)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:216)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:208)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.appendCustomMessage(ActiveNotifier.java:450)
	at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:72)
	at jenkins.plugins.slack.SlackNotifier.prebuild(SlackNotifier.java:372)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:798)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:793)
	at hudson.model.Build$BuildExecution.doRun(Build.java:145)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Dec 15, 2018 9:29:15 PM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting succeeded
Dec 15, 2018 9:29:20 PM hudson.model.Run execute
INFO: deploy_single_service #1750 main build action completed: SUCCESS
Dec 15, 2018 9:29:20 PM jenkins.plugins.slack.SlackNotifier perform
INFO: Performing complete notifications
Dec 15, 2018 9:29:21 PM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting succeeded
Dec 15, 2018 9:29:21 PM jenkins.plugins.slack.SlackNotifier perform
INFO: Performing finalize notifications
```

**Comment by timja** [comment]
Could you test this PR out please?
https://github.com/jenkinsci/slack-plugin/pull/442

**Comment by purduemike** [comment]
LGTM, Thanks!
