### ISSUE TITLE
null pointer in ActiveNotifier (2.12)

### ISSUE THREAD

**Issue by jcompagner** [jenkinsci/slack-plugin#463]
java.lang.NullPointerException
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.appendCustomMessage(ActiveNotifier.java:463)
	at jenkins.plugins.slack.ActiveNotifier.getBuildStatusMessage(ActiveNotifier.java:280)
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:145)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:434)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1835)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

seems that the new check of customMessage.isEmpty() should also test for null first..

**Comment by KrustyHack** [comment]
Got the same error here.

Plugin version 2.12 on jenkins 2.138.4.

**Comment by jhg03a** [comment]
Also verified on release 2.12.  Rolling back to 2.11 resolved the issue temporarily.

**Comment by jhg03a** [comment]
Anyone know if there's an adjustment that can be made to the slackSend command to avoid this issue too?

**Comment by mikesalvia** [comment]
I am seeing this error as well in 2.12 with Jenkins 2.86, going to attempt to roll back to 2.11 and see if that works for now.

**Comment by mikesalvia** [comment]
@jcompagner For my team, this was caused due to using custom message prior to the update to `2.12`, once we upgraded that custom message became the message for `SUCCESS` however, the other fields (`UNSTABLE` and `FAILED`) were empty. After adding the same message to the other fields the issue was resolved.

There is a workaround but this should still be fixed as there may not be a reason to use a custom message for certain build status types.

**Comment by jcompagner** [comment]
What i don't get is that from 4 dec to 20 dec so 16 days we got 8! releases
But suddenly it stopped with quite a seriours bug, that was caused because of a commit for 1 of those releases.

If somebody was so busy anyway, why not make one more release with a simple null check?

I have loads of projects over multiply folders, all configured to use slack, i don't want to change all of them (and i think we never really have a custom message?)

so @timja is it not possible to quickly make a release that fixes this regression?

**Comment by jhg03a** [comment]
Or remove the 2.12 release all together

**Comment by teluka** [comment]
same issue here...
Jenkins 2.150.1 
Slack plugin 2.12

**Comment by teluka** [comment]
@timja is there any ETA when 2.14 is going to be released ?

Thanks.

**Comment by teluka** [comment]
@timja that's awesome. Thanks a lot.
