### ISSUE TITLE
NullPointer with Custom Message

### ISSUE THREAD

**Issue by Tsaukpaetra** [jenkinsci/slack-plugin#465]
Updated to Version 2.12 from 2.9.
Apparently there's a new "Include Custom Message" box that presumably appends arbitrary text. However, it seems forced-enabled no matter what. I try to un-tick the option, but it just resets itself.
This results in a null pointer exception, since the custom message boxes are left empty (or otherwise null by default, since, you know, new feature).

I'm not sure why this is being force-enabled, but even if it was enabled with no actual custom text, there shouldn't be an exception, since this caused the build to be marked as a failure needlessly.

The error trace:

```
01:12:15 ERROR: Build step failed with exception
01:12:15 java.lang.NullPointerException
01:12:15 	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.appendCustomMessage(ActiveNotifier.java:463)
01:12:15 	at jenkins.plugins.slack.ActiveNotifier.getBuildStatusMessage(ActiveNotifier.java:280)
01:12:15 	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:145)
01:12:15 	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:434)
01:12:15 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
01:12:15 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
01:12:15 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
01:12:15 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
01:12:15 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
01:12:15 	at hudson.model.Run.execute(Run.java:1835)
01:12:15 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
01:12:15 	at hudson.model.ResourceController.execute(ResourceController.java:97)
01:12:15 	at hudson.model.Executor.run(Executor.java:429)
01:12:15 Build step 'Slack Notifications' marked build as failure
```

**Comment by KreAch3R** [comment]
Try to build with #461 in order to be able to save settings, until the maintainer comes back

**Comment by mattayes** [comment]
@KreAch3R When will the maintainer be back?

**Comment by KreAch3R** [comment]
@mattayes https://github.com/jenkinsci/slack-plugin#maintainer-away-21st-december---14th-january
