### ISSUE TITLE
Slack plugin post fails

### ISSUE THREAD

**Issue by xUrko** [jenkinsci/slack-plugin#467]
Jenkins ver. 2.156
Slack plugin 2.12

Error when posting the result:
```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Unknown Source)
	at java.util.regex.Matcher.reset(Unknown Source)
	at java.util.regex.Matcher.<init>(Unknown Source)
	at java.util.regex.Pattern.matcher(Unknown Source)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.extractReplaceLinks(ActiveNotifier.java:508)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.escape(ActiveNotifier.java:526)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.startMessage(ActiveNotifier.java:392)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.<init>(ActiveNotifier.java:307)
	at jenkins.plugins.slack.ActiveNotifier.getBuildStatusMessage(ActiveNotifier.java:269)
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:145)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:434)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1835)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by evagonz** [comment]
Ditto for us.

**Comment by alejurwal** [comment]
This is happening with Slack plugin 2.12 here too:

ERROR: Build step failed with exception 
java.lang.NullPointerException 
at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:147) 
at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:434) 
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20) 
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744) 
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690) 
at hudson.model.Build$BuildExecution.post2(Build.java:186) 
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635) 
at hudson.model.Run.execute(Run.java:1835) 
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43) 
at hudson.model.ResourceController.execute(ResourceController.java:97) 
at hudson.model.Executor.run(Executor.java:429) 
Build step 'Slack Notifications' marked build as failure

Downgraded to temporary solve the issue.

**Comment by timja** [comment]
Can you try with the 2.13 release please?

If not I'll need your config to reproduce this as I can't see what is null here,
note the other 2 posts in here are different issues

**Comment by dkder3k** [comment]
Same issue. I found out that this issue reproduces if job was created with Job DSL plugin.
i.e.:
```
freeStyleJob("can't touch this") {
    displayName("touch this")
    description("like u do")
    steps {
        shell("echo OK")
    }
    publishers {
        slackNotifier {
            startNotification(true)
            notifyFailure(true)
            notifySuccess(true)
        }
    }
}

Also if I fill advanced fields (team subdomain, integration token and channel) in slack notifications in post-build actions, all will work as expected.
Environment: Jenkins - v. 2.150.1, Slack plugin - v. 2.12

Later today I'm going to test 2.13 version

**Comment by xUrko** [comment]
Yesterday, I have updated Jenkins to 2.158 and Slack plugin to 2.13 and for now, the notification is working OK.

**Comment by timja** [comment]
@dkder3k you are missing a mandatory field in your job dsl config, in fact the only mandatory field...
`commitInfoChoice`

Closing this issue if you need more help @dkder3k please raise a new issue as its different
