### ISSUE TITLE
NumberFormatException free style job

### ISSUE THREAD

**Issue by timja** [jenkinsci/slack-plugin#506]
I have installed ver. 2.15. I have some bad and good news :). The job is still failing but we are closer to the error source. It looks it's related with Postman's CMD executor, called Newman.  See error....

```
ERROR: Build step failed with exception
java.lang.NumberFormatException: For input string: "Postman"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
**Caused: java.lang.IllegalArgumentException: can't parse argument number: Postman**
	at java.text.MessageFormat.makeFormat(Unknown Source)
	at java.text.MessageFormat.applyPattern(Unknown Source)
	at java.text.MessageFormat.<init>(Unknown Source)
	at java.text.MessageFormat.format(Unknown Source)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.escape(ActiveNotifier.java:545)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.startMessage(ActiveNotifier.java:392)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.<init>(ActiveNotifier.java:307)
	at jenkins.plugins.slack.ActiveNotifier.getBuildStatusMessage(ActiveNotifier.java:269)
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:145)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:447)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1857)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Slack Notifications' marked build as failure
```

_Originally posted by @xUrko in https://github.com/jenkinsci/slack-plugin/issues/479#issuecomment-460159782_

**Comment by timja** [comment]
@xUrko would it be possible to try out this debug build please?
https://ci.jenkins.io/job/Plugins/job/slack-plugin/job/PR-505/1/artifact/target/slack.hpi

You would need to setup a log recorder for `jenkins/plugins/slack/ActiveNotifier.java` and set it to finer

And send the results here, I'm not really sure what is causing this without knowing what the arguments are

**Comment by xUrko** [comment]
I have installed the debug build and set up a log recorder but nothing got caught. 
![image](https://user-images.githubusercontent.com/16682048/52306964-9949da80-2999-11e9-8c7f-2b99028d1831.png)

Am I missing something?

**Comment by timja** [comment]
@xUrko any luck?

**Comment by xUrko** [comment]
I was on sick leave for a couple of days....

I set logger to org.jenkinsci.plugins but this log did not return any useful information. I will try to locate with which build this issue was introduced by installed older releases....

**Comment by timja** [comment]
@xUrko if you use this test build it will always log it:
https://ci.jenkins.io/job/Plugins/job/slack-plugin/job/PR-505/2/artifact/target/slack.hpi

this code hasn't changed in a long time as far as I'm aware so best just to get the required information

might also be worth trying 2.16 there was a fix in this area

**Comment by xUrko** [comment]
I have tested with 2.3/2.9/2.12/2.16, the issue remains the same. Do have the time to check the issue via remote?

**Comment by timja** [comment]
not currently did you try with: https://ci.jenkins.io/job/Plugins/job/slack-plugin/job/PR-505/2/artifact/target/slack.hpi

**Comment by xUrko** [comment]
With this debug build, I get the following console output:

FATAL: can't parse argument number: Postman
java.lang.NumberFormatException: For input string: "Postman"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
Caused: java.lang.IllegalArgumentException: can't parse argument number: Postman
	at java.text.MessageFormat.makeFormat(Unknown Source)
	at java.text.MessageFormat.applyPattern(Unknown Source)
	at java.text.MessageFormat.<init>(Unknown Source)
	at java.text.MessageFormat.format(Unknown Source)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.escape(ActiveNotifier.java:548)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.startMessage(ActiveNotifier.java:394)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.<init>(ActiveNotifier.java:309)
	at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:70)
	at jenkins.plugins.slack.SlackNotifier.prebuild(SlackNotifier.java:459)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:798)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:793)
	at hudson.model.Build$BuildExecution.doRun(Build.java:145)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1816)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

In Jenkins log:

Feb 13, 2019 10:43:09 AM INFO jenkins.plugins.slack.SlackNotifier prebuild
Performing start notifications
Feb 13, 2019 10:43:09 AM INFO jenkins.plugins.slack.ActiveNotifier$MessageBuilder escape
Pattern is: vTime API - Client Auth - {Postman} - ORACLE, Links are: []
Feb 13, 2019 10:43:09 AM INFO jenkins.plugins.slack.SlackNotifier perform
Performing complete notifications
Feb 13, 2019 10:43:44 AM INFO jenkins.plugins.slack.SlackNotifier prebuild
Performing start notifications
Feb 13, 2019 10:43:44 AM INFO jenkins.plugins.slack.ActiveNotifier$MessageBuilder escape
Pattern is: vTime API - Client Auth - {Postman} - ORACLE, Links are: []
Feb 13, 2019 10:43:44 AM INFO jenkins.plugins.slack.SlackNotifier perform
Performing complete notifications

**Comment by timja** [comment]
Thanks this is the important bit:
```
Feb 13, 2019 10:43:09 AM INFO jenkins.plugins.slack.ActiveNotifier$MessageBuilder escape
Pattern is: vTime API - Client Auth - {Postman} - ORACLE, Links are: []
```

**Comment by timja** [comment]
I added this unit test:
```

    @Test
    public void testIssue() throws IOException {
        String input = "vTime API - Client Auth - {Postman} - ORACLE";
        String expected = "vTime API - Client Auth - {Postman} - ORACLE";
        String escaped = messageBuilder.escape(input);
        assertEquals(expected, escaped);
    }
```

It fails on 2.15

Passes on 2.16

Can you please try the newly released 2.17?

**Comment by xUrko** [comment]
Still failing...

FATAL: null
java.lang.NullPointerException
	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:71)
	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:58)
	at jenkins.plugins.slack.SlackNotifier.newSlackService(SlackNotifier.java:433)
	at jenkins.plugins.slack.ActiveNotifier.getSlack(ActiveNotifier.java:55)
	at jenkins.plugins.slack.ActiveNotifier.notifyStart(ActiveNotifier.java:96)
	at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:74)
	at jenkins.plugins.slack.SlackNotifier.prebuild(SlackNotifier.java:456)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:798)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:793)
	at hudson.model.Build$BuildExecution.doRun(Build.java:145)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1816)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

**Comment by timja** [comment]
That's something different,
```
this.roomIds = roomId.split("[,; ]+");
```

Which means you haven't set a channel, it should error higher up and not with a null pointer exception.

**Comment by xUrko** [comment]
I have re-checked Slack settings under System configuration and find out that they were completely wiped out. I am not sure what caused such situation. When I have re-set the settings, the Slack notification started working again.

**Comment by timja** [comment]
Ok, closing since the unit test proves this issue was resolved
