### ISSUE TITLE
NPE in ActiveNotifier.java:147 (ver 2.17, Jenkins: 2.164)

### ISSUE THREAD

**Issue by bra-fsn** [jenkinsci/slack-plugin#522]
After upgrading from 2.3, we have a lot of errors with the slack notification plugin.
For example this happens occasionally:
```Build step 'Execute shell' marked build as failure
ERROR: Build step failed with exception
java.lang.NullPointerException
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:147)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:444)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1863)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Slack Notifications' marked build as failure
```
While sometimes it just a NullPointerException without any traces:
```Build step 'Execute shell' marked build as failure
ERROR: Build step failed with exception
java.lang.NullPointerException
Build step 'Slack Notifications' marked build as failure
```

The error occurs sporadically, not with every builds.

**Comment by timja** [comment]
That line maps to:
```
if (notifier.getCommitInfoChoice().showAnything()) {
```

That means your commitInfoChoice hasn't been chosen, this should be impossible through the UI
That is the only mandatory field.

How are your jobs created?

**Comment by bra-fsn** [comment]
Via job DSL plugin and you're right, it's not specified. We've tried sending failure events and it worked, so I'm uncertain on this. Trying to add this (commitInfoChoice('NONE')) to all slackNotifier{} blocks and will get back.
Thanks,

**Comment by bra-fsn** [comment]
As it turned out, we tried it with a test job, set up in Jenkins which of course had this field set. That mislead me, because I thought it was generated with the job DSL plugin.
Sorry for the noise.
