### ISSUE TITLE
NPE in 2.18 (Jenkins ver. 2.161)

### ISSUE THREAD

**Issue by vikulin** [jenkinsci/slack-plugin#528]
java.lang.NullPointerException
	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:72)
	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:59)
	at jenkins.plugins.slack.SlackNotifier.newSlackService(SlackNotifier.java:431)
	at jenkins.plugins.slack.SlackNotifier.lambda$slackFactory$0(SlackNotifier.java:464)
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:142)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:445)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1857)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Slack Notifications' marked build as failure

This exception maps to:
    @Override
    public boolean perform(AbstractBuild<?, ?> build, Launcher launcher, BuildListener listener) {
        String buildKey = BuildKey.format(build);
        BuildAwareLogger log = createLogger(listener);
        log.debug(buildKey, "Performing complete notifications");
        JenkinsTokenExpander tokenExpander = new JenkinsTokenExpander(listener);
-->>new ActiveNotifier(this, slackFactory(listener), log, tokenExpander).completed(build);
        if (notifyRegression) {
            log.debug(buildKey, "Performing finalize notifications");
            new ActiveNotifier(this, slackFactory(listener), log, tokenExpander).finalized(build);
        }
        return true;
    }

**Comment by timja** [comment]
Should be fixed in https://github.com/jenkinsci/slack-plugin/pull/541
