### ISSUE TITLE
java.lang.NullPointerException - Build step 'Slack Notifications' marked build as failure

### ISSUE THREAD

**Issue by ghost** [jenkinsci/slack-plugin#530]
We've setup Slack Notifications Plugin and getting NullPointerException Errors sometimes.

![bildschirmfoto 2019-02-28 um 09 49 20](https://user-images.githubusercontent.com/1019812/53553575-4699b380-3b3e-11e9-9b47-0c9478840d74.png)

The recent build-job history looks like

![bildschirmfoto 2019-02-28 um 09 49 08](https://user-images.githubusercontent.com/1019812/53553598-52857580-3b3e-11e9-8784-b9f684fcde58.png)

And the log looks like

```
09:45:43 FATAL: null
09:45:43 java.lang.NullPointerException
09:45:43 	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:72)
09:45:43 	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:59)
09:45:43 	at jenkins.plugins.slack.SlackNotifier.newSlackService(SlackNotifier.java:431)
09:45:43 	at jenkins.plugins.slack.SlackNotifier.lambda$slackFactory$0(SlackNotifier.java:464)
09:45:43 	at jenkins.plugins.slack.ActiveNotifier.notifyStart(ActiveNotifier.java:88)
09:45:43 	at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:69)
09:45:43 	at jenkins.plugins.slack.SlackNotifier.prebuild(SlackNotifier.java:458)
09:45:43 	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:798)
09:45:43 	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:793)
09:45:43 	at hudson.model.Build$BuildExecution.doRun(Build.java:145)
09:45:43 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
09:45:43 	at hudson.model.Run.execute(Run.java:1816)
09:45:43 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:45:43 	at hudson.model.ResourceController.execute(ResourceController.java:97)
09:45:43 	at hudson.model.Executor.run(Executor.java:429)
09:45:43 Discard old builds...
09:45:43 #9 is removed because old than numToKeep
09:45:58 [Slack Notifications] found #72 as previous completed, non-aborted build
09:45:58 [Slack Notifications] will send OnSingleFailureNotification because build matches and user preferences allow it
09:45:58 ERROR: Build step failed with exception
09:45:58 java.lang.NullPointerException
09:45:58 	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:72)
09:45:58 	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:59)
09:45:58 	at jenkins.plugins.slack.SlackNotifier.newSlackService(SlackNotifier.java:431)
09:45:58 	at jenkins.plugins.slack.SlackNotifier.lambda$slackFactory$0(SlackNotifier.java:464)
09:45:58 	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:142)
09:45:58 	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:445)
09:45:58 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
09:45:58 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
09:45:58 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
09:45:58 	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
09:45:58 	at hudson.model.Run.execute(Run.java:1863)
09:45:58 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:45:58 	at hudson.model.ResourceController.execute(ResourceController.java:97)
09:45:58 	at hudson.model.Executor.run(Executor.java:429)
09:45:58 Build step 'Slack Notifications' marked build as failure
09:45:58 Finished: FAILURE
```

We hope anyone knows a solution onto this issue, it's really annoying...

**Comment by chinhodado** [comment]
Same error here:

```
[Slack Notifications] found #7366 as previous completed, non-aborted build
[Slack Notifications] will send OnSingleFailureNotification because build matches and user preferences allow it
ERROR: Build step failed with exception
java.lang.NullPointerException
	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:72)
	at jenkins.plugins.slack.StandardSlackService.<init>(StandardSlackService.java:59)
	at jenkins.plugins.slack.SlackNotifier.newSlackService(SlackNotifier.java:431)
	at jenkins.plugins.slack.SlackNotifier.lambda$slackFactory$0(SlackNotifier.java:464)
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:142)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:445)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1863)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Slack Notifications' marked build as failure
Finished: FAILURE
```

**Comment by sghill** [comment]
Looks like the room is coming through as null from the stacktrace pointing to [here](https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L72). Is the room configured globally, in the job, or both?

Same issue as #528.

**Comment by Gildon** [comment]
@captrespect Same. Probably wiped in the update.

**Comment by timja** [comment]
Closing as channel needs to be set

**Comment by regetskcob** [comment]
@timja Not sure, whether the solution is *that* easy. We're just getting the crash, when I activate "Notify Build Start". When it's deactivated, all other notifications are sent fine.

Will notify out Sys-Admin to check the fields mentioned above.

**Comment by timja** [comment]
Will re-open for now,
the line of code in question is:
```
this.roomIds = roomId.split("[,; ]+");
```

The only way for that to fail is if the channel isn't set

**Comment by timja** [comment]
There's a separate issue for a better error message:
https://github.com/jenkinsci/slack-plugin/issues/517

**Comment by timja** [comment]
better error message has been added
