### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by tersmitten** [jenkinsci/slack-plugin#557]
```
FATAL: null
java.lang.NullPointerException
	at jenkins.plugins.slack.SlackMatrixBridge$1.startBuild(SlackMatrixBridge.java:19)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.notifyStartBuild(DefaultMatrixExecutionStrategyImpl.java:214)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.run(DefaultMatrixExecutionStrategyImpl.java:129)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:375)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1818)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
FATAL: null
java.lang.NullPointerException
	at jenkins.plugins.slack.SlackMatrixBridge$1.endBuild(SlackMatrixBridge.java:29)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.post2(MatrixBuild.java:433)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1843)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

### Your checklist for this issue

- [x] Jenkins version, 2.172

- [x] Plugin version, 2.21

- [x] OS, Ubuntu 16.04

### Description

After installing the latest version all my builds fail. Downgrading to `2.2.0` fixes the problem

**Comment by timja** [comment]
Sorry for that, workaround is to install `matrix-project` plugin.
Working on fixing it currently
