### ISSUE TITLE
A JSONObject text must begin with '{' at 1 [character 2 line 1]

### ISSUE THREAD

**Issue by sarthak1996** [jenkinsci/slack-plugin#601]
- [x] 2.185 Jenkins version

- [x] 2.27 Slack Notification Plugin

- [x] Oracle Linux Server release 6.8
 ``` lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:g                                                                             raphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: OracleServer
Description:    Oracle Linux Server release 6.8
Release:        6.8
Codename:       n/a
```

### Description

Hi I am facing issues while posting message to a slack channel. I read some threads where it is mentioned that only bot user should be selected and Slack Compatible Url should be left empty and the same is not working for me.

Please find the slack configuration:
![image](https://user-images.githubusercontent.com/8405092/62761318-fbe47600-baa3-11e9-8d3b-9ac57e5e80ae.png)

In the logs following stacktrace is coming up:

````
Posting: to #channelname on workspacename using https://slack.com/api/chat.postMessage: [{"fallback":"Slack/Jenkins plugin: you're all set on http://indl88026.in.oracle.com:8080/Jenkins/","color":"good","fields":[{"short":false,"value":"Slack/Jenkins plugin: you're all set on http://indl88026.in.oracle.com:8080/Jenkins/"}],"mrkdwn_in":["pretext","text","fields"]}] good
Aug 09, 2019 12:38:57 PM INFO jenkins.plugins.slack.StandardSlackService getHttpClient
Using proxy authentication (user=admin)
Aug 09, 2019 12:38:58 PM WARNING jenkins.plugins.slack.StandardSlackService publish
Error posting to Slack
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:214)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:140)
	at jenkins.plugins.slack.SlackNotifier$DescriptorImpl.doTestConnection(SlackNotifier.java:862)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:36)
	at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)
	at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)`

```

**Comment by timja** [comment]
Try unticking bot user?

**Comment by sarthak1996** [comment]
Still getting the same error after unticking the bot user

**Comment by casz** [comment]
And what if you remove Username?

**Comment by sarthak1996** [comment]
After removing user too, the error persists

**Comment by timja** [comment]
There's a work around in 2.29 that should hopefully stop this failing.
(I've just released it now)

**Comment by casz** [comment]
@timja not sure you released anything 😆 
![image](https://user-images.githubusercontent.com/1661688/62768511-490e1b00-ba97-11e9-858e-45d46e1ca994.png)

**Comment by timja** [comment]
🤦‍♂ I misread the pending changes in release drafter, just forgot to publish them last time 🤕

**Comment by timja** [comment]
this should be fixed on master
