### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant jenkins.plugins.slack.CommitInfoChoice.

### ISSUE THREAD

**Issue by dave-tock** [jenkinsci/slack-plugin#607]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description

Jenkins 2.187
Plugin 2.29
OS Debian Stable

We can no longer configure new slack notifications, or reconfigure existing ones. Attempting to save the configuration in the UI throws the exception listed below.

The core complaint in the exception is that `commitInfoChoice` is unset. The problem is, the dropdown for field "Notification message includes" in the UI has no values (i.e. if you click the dropdown, it's an empty list).

This affects both new projects that we create from scratch, and existing projects (can no longer edit the configuration without getting the exception).

We don't really know where to start debugging this. For whatever reason, it seems the enum values aren't getting plumbed through to the UI. Any ideas on how to fix?

```
java.lang.IllegalArgumentException: No enum constant jenkins.plugins.slack.CommitInfoChoice.
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:733)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:778)
Caused: java.lang.IllegalArgumentException: Failed to convert the commitInfoChoice parameter of the constructor public jenkins.plugins.slack.SlackNotifier(jenkins.plugins.slack.CommitInfoChoice)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:780)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:678)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class jenkins.plugins.slack.SlackNotifier from {"startNotification":false,"notifySuccess":false,"notifyAborted":false,"notifyNotBuilt":false,"notifyUnstable":false,"notifyRegression":false,"notifyEveryFailure":false,"notifyBackToNormal":false,"notifyFailure":false,"notifyRepeatedFailure":false,"includeTestSummary":false,"includeFailedTests":false,"includeCustomMessage":false,"customMessage":"","customMessageSuccess":"","customMessageAborted":"","customMessageNotBuilt":"","customMessageUnstable":"","customMessageFailure":"","commitInfoChoice":"","baseUrl":"","teamDomain":"","authToken":"","tokenCredentialId":"","botUser":false,"iconEmoji":"","username":"","room":"","stapler-class":"jenkins.plugins.slack.SlackNotifier","$class":"jenkins.plugins.slack.SlackNotifier"}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:681)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:474)
	at hudson.model.Descriptor.newInstance(Descriptor.java:596)
Caused: java.lang.Error: Failed to instantiate class jenkins.plugins.slack.SlackNotifier from {"startNotification":false,"notifySuccess":false,"notifyAborted":false,"notifyNotBuilt":false,"notifyUnstable":false,"notifyRegression":false,"notifyEveryFailure":false,"notifyBackToNormal":false,"notifyFailure":false,"notifyRepeatedFailure":false,"includeTestSummary":false,"includeFailedTests":false,"includeCustomMessage":false,"customMessage":"","customMessageSuccess":"","customMessageAborted":"","customMessageNotBuilt":"","customMessageUnstable":"","customMessageFailure":"","commitInfoChoice":"","baseUrl":"","teamDomain":"","authToken":"","tokenCredentialId":"","botUser":false,"iconEmoji":"","username":"","room":"","stapler-class":"jenkins.plugins.slack.SlackNotifier","$class":"jenkins.plugins.slack.SlackNotifier"}
	at hudson.model.Descriptor.newInstance(Descriptor.java:604)
	at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:1059)
	at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:1021)
	at hudson.util.DescribableList.rebuildHetero(DescribableList.java:208)
	at hudson.model.Project.submit(Project.java:231)
	at hudson.model.Job.doConfigSubmit(Job.java:1349)
	at hudson.model.AbstractProject.doConfigSubmit(AbstractProject.java:772)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:797)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by timja** [comment]
No idea, I've just tried on that jenkins version and works fine for me,
I would try uninstalling and reinstalling the plugin or restarting jenkins.
seems like the plugin is corrupt

**Comment by dave-tock** [comment]
Tried uninstalling/reinstalling the plugin, as well as restarting jenkins (both during the plugin reinstall, and separately). Unfortunately, still broken, the commitInfoChoice dropdown is still empty :(

**Comment by timja** [comment]
Un-able to reproduce, is this still happening?

**Comment by dave-tock** [comment]
It is still happening. I don't know what else I can provide, unfortunately :(

**Comment by timja** [comment]
SlackNotifier.xml ? also try deleting it to see if it helps?

**Comment by dave-tock** [comment]
Figured it out. It was nothing to do with the plugin. Our frontend reverse proxy was blocking some of Jenkins's XHRs. Just enough to break the slack-notifier plugin configuration UI, but not enough for anything else to be noticeably broken. Doh.

Sorry for the noise, and thank you for the help!
