### ISSUE TITLE
slackSend stopped working for some channels

### ISSUE THREAD

**Issue by armandfp** [jenkinsci/slack-plugin#687]
### Your checklist for this issue

- [x] Jenkins version: 2.233

- [x] Plugin version: 2.40

- [x] OS Centos 7.6

### Description
Last Monday we upgraded the version of jenkins, after that the slackSend function stop working for some channels.

We setup Jenkins CI app a long ago, on the channel part we specify # build_channel, and that it's working, if I use a Jenkinsfile with no channel data, it goes to that one.

We also have some other pipelines where we specified the channel, example # notifications_internal, and that stopped working after the jenkins upgrade.

I enabled logs for this plugin, for the default channel i got:
```
Apr 24, 2020 12:35:35 PM FINE jenkins.plugins.slack.StandardSlackService
Posting: to #build_channel on <my-dt>:  {"attachments":[{"fallback":"this is a test, ignore","color":"#439FE0","fields":[{"short":false,"value":"this is a test, ignore"}],"mrkdwn_in":["pretext","text","fields"]}],"link_names":"1","unfurl_links":"true","unfurl_media":"true","channel":"#build_channel","as_user":"true"}
Apr 24, 2020 12:35:35 PM FINE jenkins.plugins.slack.StandardSlackService
Posting succeeded
```

when I specify a channel I get:
```
Apr 24, 2020 12:46:48 PM FINE jenkins.plugins.slack.StandardSlackService
Posting: to #notifications_internal on <my-dt>:  {"attachments":[{"fallback":"this is a test, ignore","color":"#439FE0","fields":[{"short":false,"value":"this is a test, ignore"}],"mrkdwn_in":["pretext","text","fields"]}],"link_names":"1","unfurl_links":"true","unfurl_media":"true","channel":"#notifications_internal","as_user":"true"}
Apr 24, 2020 12:46:48 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Slack post may have failed. Response: null
Apr 24, 2020 12:46:48 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Response Code: 403
```

any ideas what could be the problem?

**Comment by timja** [comment]
try invite the app into your channel

**Comment by armandfp** [comment]
it looks like there is no way to invite an app to the channel, only add the app to the workspace, and it's there

**Comment by NBE-SG** [comment]
no clue if this contains some useful info for you : https://github.com/jenkinsci/slack-plugin/issues/683
maybe chat:write.public ?

**Comment by jetersen** [comment]
@armandfp for private channels you still need to invite apps by doing `/invite @yourapp`

**Comment by armandfp** [comment]
@NBE-SG we are using with botUser: false, and the default channel is a private one, the channel with the problem is public.
@jetersen I tried, but @Jenkins doesnt appears.

**Comment by jetersen** [comment]
Then you should reach out to slack support as they are the once maintaining the Jenkins slack app.

**Comment by NBE-SG** [comment]
Well you have a "Response Code: 403" error, looks like you might use wrong credentials, but you said that it could still post to some channels so it's weird.

**Comment by NBE-SG** [comment]
By the way you can invite app to a channel by going on it's profile :
go to **Applications** on the left menu,
click on **your app**,
top right corner click **Details**,
click **More** on the right pane,
click **Add to channel**

**Comment by Tenzian** [comment]
I'm also having the same issue on Jenkins 2.234

Updating the slack plugin to 2.40 stopped Jenkins being able to connect to slack (pressing _test connection_ in Configure System resulted in a failure)

Rolling back to 2.39 instantly fixed it without having to re-invite anything to the channel or change any credentials.

**Comment by timja** [comment]
That's very strange, but do you have any details on log messages

https://github.com/jenkinsci/slack-plugin#troubleshooting-connection-failure

**Comment by Tenzian** [comment]
The error is (channel name and server name edited for anonymity):
```
May 05, 2020 5:25:40 PM FINE jenkins.plugins.slack.StandardSlackService
Posting: to #jenkins on myslackchannel:  {"attachments":[{"fallback":"Slack/Jenkins plugin: you're all set on https://my.jenkins.server:8080/","color":"good","fields":[{"short":false,"value":"Slack/Jenkins plugin: you're all set on https://my.jenkins.server:8080/"}],"mrkdwn_in":["pretext","text","fields"]}],"link_names":"1","unfurl_links":"true","unfurl_media":"true","channel":"#jenkins","as_user":"true"}
May 05, 2020 5:25:40 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Error posting to Slack
java.net.SocketException: SOCKS: Connection not allowed by ruleset
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:553)
    at java.net.Socket.connect(Socket.java:589)
    at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:401)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
    at jenkins.plugins.slack.StandardSlackService.postToSlack(StandardSlackService.java:177)
    at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:269)
    at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:308)
    at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:280)
    at jenkins.plugins.slack.SlackNotifier$DescriptorImpl.doTestConnection(SlackNotifier.java:908)
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
    at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
    at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
    at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
    at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:36)
    at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)
    at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)
    at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
    at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
    at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
    at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
    at org.jenkinsci.plugins.corsfilter.AccessControlsFilter.doFilter(AccessControlsFilter.java:79)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
    at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:113)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
    at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
    at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
    at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
    at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
    at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
    at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
    at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
    at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
    at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
    at org.eclipse.jetty.server.Server.handle(Server.java:500)
    at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
    at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
    at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
    at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by timja** [comment]
That looks networking related =/

`SOCKS: Connection not allowed by ruleset`

you must be behind a proxy, possibly it's blocking access to slack or doesn't support the TLS 1.2 that's now required

**Comment by Tenzian** [comment]
Yes, definitely behind a proxy - though I can curl a payload to https://hooks.slack.com fine using it, e.g:

`curl -x http://my.proxy:80 -X POST --data-urlencode 'payload={"text": "messageText"}' https://hooks.slack.com/services/REDACTED`

**Comment by armandfp** [comment]
the problem that @Tenzian described is not related.

I try to downgrade to the version 2.39 and it's the same problem.
I need to make clear something:

[private] #build_channel => it works (default channel defined in slack)
[private] #build_channel_uat => it works
[private] #build_devops => it works
[private] #slack_testing => it doesn't work (response null, 403)
[public] #notifications_internal => it doesn't work (response null, 403)
[public] #kibana_errors => it doesn't work (response null, 403)

it doesn't make any sense to me, do you have an idea how i can debug this?

**Comment by timja** [comment]
best to try reproduce it with curl, extract out the request that's being made and try do it yourself when you'll get all the response information

**Comment by armandfp** [comment]
I did a curl and I got:

[private] #build_channel => 200 "ok"
[public] #notifications_internal => 403 "invalid_channel"
[private] #slack_testing => 403 "action_prohibited"

The error in the logs are wrong, because in those cases slack returns an string, and I think the plugin will try to parse it:
https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L181

it should be better for debugging to show the response that slack sent.

At the end it's not a problem of this plugin, it's slack response; before I close this thread, do you know how i can get the list of channels? or how I can get more info why my channel was marked as invalid?

As you can see I'm still using the Jenkins-ci app, should I change to bot user and do my app on slack? I noticed in the documentation of this plugin that this jenkins-ci app from slack is old and not maintained anymore.

**Comment by timja** [comment]
You would have to ask slack support, they support the built in app,

If you use the custom app there’s more features available and it just uses slacks regular api rather then the app that they’ve created in their code with its own custom api

**Comment by jetersen** [comment]
Perhaps we should update the docs to recommend using a bot user over using the existing slack app?

**Comment by timja** [comment]
> Perhaps we should update the docs to recommend using a bot user over using the existing slack app?

possibly the docs are a lot better now and lots more features, making it the default recommended would make sense

**Comment by armandfp** [comment]
ok then, thank you @timja and @jetersen  for your answers!

**Comment by timja** [comment]
> I did a curl and I got:
> 
> [private] #build_channel => 200 "ok"
> [public] #notifications_internal => 403 "invalid_channel"
> [private] #slack_testing => 403 "action_prohibited"
> 
> The error in the logs are wrong, because in those cases slack returns an string, and I think the plugin will try to parse it:
> [/src/main/java/jenkins/plugins/slack/StandardSlackService.java@`master`#L181](https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L181) [](/jenkinsci/slack-plugin/blob/HEAD@{2020-05-06T11:40:18Z}/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L181)
> 

It should catch the error and still log it though: https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L187

**Comment by armandfp** [comment]
responseString returns null, and I think it's because it tries to parse a json? EntityUtils.toString(entity);

**Comment by timja** [comment]
> responseString returns null, and I think it's because it tries to parse a json? EntityUtils.toString(entity);

that should just return the string, a couple of lines down it tries to convert it to json

**Comment by armandfp** [comment]
then there is a problem because as you can see, in the logs just shows null, but from curl i got an string.
