### ISSUE TITLE
Slack Jenkins Test Connection => Failure

### ISSUE THREAD

**Issue by Sateesh16683** [jenkinsci/slack-plugin#713]
### Your checklist for this issue

- [x] Jenkins version
We are with Jenkins version 2.239
- [x] Plugin version
Slack plugin version 2.4
- [x] OS
Centos7

### Description

Installed slack notification plugin version 2.4 to send Jenkins to build updated to slack channel.
Did the configuration and when doing the test connection it is failing. 
I tried all possible ways to configure with different channels. but getting the same issue.

Could someone please have a look on it.

**Comment by timja** [comment]
do you mean 2.40?

Please provide your configuration, what you've done, and also check the server logs.

**Comment by Sateesh16683** [comment]
Yes..we are with slack notification plugin version as 2.40.

Here is the server log
```
Jul 29, 2020 8:27:55 AM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Error posting to Slack
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:159)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2041)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1145)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at jenkins.plugins.slack.StandardSlackService.postToSlack(StandardSlackService.java:177)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:269)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:308)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:280)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:361)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:258)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```
<img width="1344" alt="Screenshot 2020-07-29 at 2 04 40 PM" src="https://user-images.githubusercontent.com/58687771/88777535-f3011e80-d1a4-11ea-8671-0777c1762472.png">
<img width="1590" alt="Screenshot 2020-07-29 at 2 06 16 PM" src="https://user-images.githubusercontent.com/58687771/88777553-f98f9600-d1a4-11ea-8a13-12ad93e38113.png">

**Comment by timja** [comment]
Well that looks like the error, 

Make sure your java installation can connect over TLS 1.2:
https://api.slack.com/changelog/2019-07-deprecate-early-tls-versions

**Comment by Sateesh16683** [comment]
We are with java 8.
```
[sate7678@661635-a-build2 ~]$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
[sate7678@661635-a-build2 ~]$ 
```

I think for Java 8 ,  TLS 1.2 is enabled by default.

**Comment by jetersen** [comment]
As previously noted in another issue it can be related to the OS used.

**Comment by Sateesh16683** [comment]
Is it possible to downgrade my slack plugin version from 2.4 to 2.3  and how?
In my Jenkins, it's not showing option to downgrade the plugin version.

It was working well for me with 2.4 version earlier.

**Comment by jetersen** [comment]
2.40 did not change anything in regards to https calls

**Comment by Sateesh16683** [comment]
the, what might be the issue? 
it was working well till last week..not it's not working.
Today morning tried reconfiguring .still getting the same issue.

**Comment by timja** [comment]
do you have a proxy ? or do you connect directly?

**Comment by jetersen** [comment]
So your literal with saying using version `2.4`? That version is almost 2 years old.

I'd suggest trying out the latest version as `2.39` which introduced an partial fix, that ensures TLS 1.2 is enabled in the apache2 library.

**Comment by Sateesh16683** [comment]
connecting directly. I don't have a proxy.

**Comment by Sateesh16683** [comment]
> So your literal with saying using version `2.4`? That version is almost 2 years old.
> 
> I'd suggest trying out the latest version as `2.39` which introduced an partial fix, that ensures TLS 1.2 is enabled in the apache2 library.

How can I downgrade plugin from 2.40 to 2.39?

**Comment by jetersen** [comment]
No need to downgrade if your already using `2.40` should have the same fix

**Comment by Sateesh16683** [comment]
> No need to downgrade if your already using `2.40` should have the same fix

Ohh okay...Could you please suggest some fix for this issue. I am unable to move further on this.

**Comment by jetersen** [comment]
https://github.com/jenkinsci/slack-plugin/issues/673#issuecomment-596918770 perhaps check your java parameters

**Comment by jetersen** [comment]
You could also enable debug and see what's going on: `-Djavax.net.debug=ssl,handshake`

**Comment by Sateesh16683** [comment]
It's working after downgrading the slack plugin from 2.4 to 2.38.
closing the ticket.
thank you!
