### ISSUE TITLE
slackUserIdFromEmail throws exception

### ISSUE THREAD

**Issue by PazerOP** [jenkinsci/slack-plugin#726]
### Your checklist for this issue

- [x] Jenkins version: 2.235.5

- [x] Plugin version: 2.41

- [x] OS: Windows 10 1909

### Description

Please describe your issue here.

I have the following bit of code in my pipeline file:

```groovy
def authorEmail = author.getProperty(hudson.tasks.Mailer.UserProperty.class).getAddress();
echo "authorEmail = ${authorEmail}"
//def authorID = slackUserIdFromEmail(authorEmail);
```

All is well, and it prints out my email address. But if I uncomment the `slackUserIdFromEmail` line, I get the following exception:

```
14:54:28  an exception which occurred:
14:54:28  	in field com.cloudbees.groovy.cps.impl.FunctionCallEnv.locals
14:54:28  	in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@18efec0
14:54:28  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
14:54:28  	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@16e050a
14:54:28  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
14:54:28  	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@63a3ed
14:54:28  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
14:54:28  	in object com.cloudbees.groovy.cps.impl.LoopBlockScopeEnv@18b105c
14:54:28  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
14:54:28  	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@1f9e03f
14:54:28  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
14:54:28  	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@97ed36
14:54:28  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
14:54:28  	in object com.cloudbees.groovy.cps.impl.LoopBlockScopeEnv@d26060
14:54:28  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
14:54:28  	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@1e66ac6
14:54:28  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
14:54:28  	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@fea16a
14:54:28  	in field com.cloudbees.groovy.cps.impl.CallEnv.caller
14:54:28  	in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@10ed132
14:54:28  	in field com.cloudbees.groovy.cps.Continuable.e
14:54:28  	in object org.jenkinsci.plugins.workflow.cps.SandboxContinuable@29905e
14:54:28  	in field org.jenkinsci.plugins.workflow.cps.CpsThread.program
14:54:28  	in object org.jenkinsci.plugins.workflow.cps.CpsThread@1889586
14:54:28  	in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.threads
14:54:28  	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@48457c
14:54:28  	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@48457c
14:54:28  Caused: java.io.NotSerializableException: hudson.scm.SubversionChangeLogSet
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:926)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:568)
14:54:28  	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
14:54:28  	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
14:54:28  	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
14:54:28  	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
14:54:28  	at java.io.ObjectOutputStream.writeObject(Unknown Source)
14:54:28  	at java.util.HashMap.internalWriteEntries(Unknown Source)
14:54:28  	at java.util.HashMap.writeObject(Unknown Source)
14:54:28  	at sun.reflect.GeneratedMethodAccessor500.invoke(Unknown Source)
14:54:28  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
14:54:28  	at java.lang.reflect.Method.invoke(Unknown Source)
14:54:28  	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callWriteObject(JDKSpecific.java:156)
14:54:28  	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:191)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1028)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
14:54:28  	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
14:54:28  	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
14:54:28  	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
14:54:28  	at java.io.ObjectOutputStream.writeObject(Unknown Source)
14:54:28  	at java.util.concurrent.ConcurrentSkipListMap.writeObject(Unknown Source)
14:54:28  	at sun.reflect.GeneratedMethodAccessor520.invoke(Unknown Source)
14:54:28  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
14:54:28  	at java.lang.reflect.Method.invoke(Unknown Source)
14:54:28  	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callWriteObject(JDKSpecific.java:156)
14:54:28  	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:191)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1028)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
14:54:28  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
14:54:28  	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
14:54:28  	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
14:54:28  	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.lambda$writeObject$0(RiverWriter.java:144)
14:54:28  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:237)
14:54:28  	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.writeObject(RiverWriter.java:143)
14:54:28  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:553)
14:54:28  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:530)
14:54:28  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgramIfPossible(CpsThreadGroup.java:517)
14:54:28  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:441)
14:54:28  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
14:54:28  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
14:54:28  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
14:54:28  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
14:54:28  	at java.util.concurrent.FutureTask.run(Unknown Source)
14:54:28  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
14:54:28  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
14:54:28  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
14:54:28  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
14:54:28  	at java.util.concurrent.FutureTask.run(Unknown Source)
14:54:28  	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14:54:28  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14:54:28  	at java.lang.Thread.run(Unknown Source)
14:54:28  Finished: FAILURE
```

**Comment by stuartrowe** [comment]
How are you retrieving `author`? Looks like calling the `slackUserIdFromEmail` step is causing the pipeline to be serialized out. This is catching non-serializable objects like `hudson.scm.SubversionChangeLogSet`.

I would suggest moving the bit of code that retrieves `author` and then `authorEmail` into a `@NonCPS` annotated method:

```
def authorEmail = getAuthorEmail(); // call new @NonCPS method
echo "authorEmail = ${authorEmail}"
def authorID = slackUserIdFromEmail(authorEmail);
```

**Comment by PazerOP** [comment]
My full function looks like this. I'm very much a jenkins novice, I'm not exactly sure how to pull out the code you mention into a method that wouldn't still be having a reference to the `hudson.scm.SubversionChangeLogSet`:

```groovy
def pazerGetChangeMessage(changeSets)
{
	if (changeSets.size() < 1)
		return "No changes."

	def changeMessage = "Changes:";
	for (int i = 0; i < changeSets.size(); i++)
	{
		def entries = changeSets[i].items
		for (int j = 0; j < entries.length; j++)
		{
			def entry = entries[j]
			def author = entry.author;
			def authorEmail = author.getProperty(hudson.tasks.Mailer.UserProperty.class).getAddress();
			echo "authorEmail = ${authorEmail}"
			def authorID = slackUserIdFromEmail(authorEmail);
			changeMessage = "${changeMessage}\t${entry.commitId} by ${entry.author} (<@${authorID}>): ${entry.msg}"
			def files = new ArrayList(entry.affectedFiles)
			for (int k = 0; k < files.size(); k++)
			{
				def file = files[k]
				changeMessage = "${changeMessage}\n\t\t${file.editType.name} ${file.path}"
			}
		}
	}

	return changeMessage;
}
```

Used like:

```groovy
slackSend(message: "${pazerGetChangeMessage(currentBuild.changeSets)}")
```
