### ISSUE TITLE
SlackNotifier circular dependency warning

### ISSUE THREAD

**Issue by mecseid** [jenkinsci/slack-plugin#746]
### Checklist for this issue
* [x] Jenkins version: <br> 2.263.1
* [x] Plugin version: <br> 2.45
* [x] OS: <br> jenkins:lts container

### Description
I installed the Slack Notification plugin, and after the Jenkins restart, I got the following stacktrace.
```
2020-12-10 11:31:48.381+0000 [id=26]	WARNING	h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=jenkins.plugins.slack.SlackNotifier$DescriptorImpl, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Tried proxying jenkins.plugins.slack.SlackNotifier$DescriptorImpl to support a circular dependency, but it is not an interface.
1 error
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:440)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:402)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:393)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:346)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.iterator(ExtensionList.java:172)
	at jenkins.model.Jenkins.getDescriptor(Jenkins.java:1582)
	at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1597)
	at hudson.model.AbstractDescribableImpl.getDescriptor(AbstractDescribableImpl.java:42)
	at org.jenkinsci.plugins.matrixauth.AuthorizationContainer.add(AuthorizationContainer.java:86)
	at org.jenkinsci.plugins.matrixauth.AbstractAuthorizationContainerConverter.unmarshalContainer(AbstractAuthorizationContainerConverter.java:82)
	at org.jenkinsci.plugins.matrixauth.AbstractAuthorizationContainerConverter.unmarshal(AbstractAuthorizationContainerConverter.java:94)
	at hudson.util.XStream2$AssociatedConverterImpl.unmarshal(XStream2.java:464)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:408)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:330)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:269)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:408)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:330)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:269)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:408)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:330)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:269)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:408)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:330)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:269)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1189)
	at hudson.util.XStream2.unmarshal(XStream2.java:161)
	at hudson.util.XStream2.unmarshal(XStream2.java:132)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1173)
	at hudson.XmlFile.unmarshal(XmlFile.java:180)
	at hudson.XmlFile.unmarshal(XmlFile.java:163)
	at hudson.model.Descriptor.load(Descriptor.java:913)
	at jenkins.plugins.slack.SlackNotifier$DescriptorImpl.<init>(SlackNotifier.java:651)
	at jenkins.plugins.slack.SlackNotifier$DescriptorImpl$$FastClassByGuice$$c95f1661.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:572)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:440)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:402)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:393)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:346)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.iterator(ExtensionList.java:172)
	at jenkins.model.Jenkins.getDescriptorByType(Jenkins.java:1607)
	at hudson.plugins.git.GitSCM.onLoaded(GitSCM.java:2075)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The plugin works as exptected, but every time I have to restart the Jenkins server, this warning message shows up.

**Comment by timja** [comment]
What's in your slack configuration file?

**Comment by mecseid** [comment]
Do you think for jenkins.plugins.slack.SlackNotifier.xml file?

Content of the file:
```
<?xml version='1.1' encoding='UTF-8'?>
<jenkins.plugins.slack.SlackNotifier_-DescriptorImpl plugin="slack@2.40">
  <baseUrl></baseUrl>
  <teamDomain><!-- removed --></teamDomain>
  <tokenCredentialId>slack</tokenCredentialId>
  <botUser>true</botUser>
  <sendAsText>false</sendAsText>
  <iconEmoji></iconEmoji>
  <username></username>
  <room></room>
  <slackUserIdResolver class="jenkins.plugins.slack.user.EmailSlackUserIdResolver">
    <mailAddressResolvers class="hudson.ExtensionList">
      <hudson>
        <!-- I removed the whole hudson configuration, I don't know why it is here. -->
      </hudson>
      <jenkins class="hudson.model.Hudson" reference="../hudson"/>
      <extensionType>hudson.tasks.MailAddressResolver</extensionType>
      <listeners class="java.util.concurrent.CopyOnWriteArrayList"/>
      <legacyInstances/>
    </mailAddressResolvers>
  </slackUserIdResolver>
</jenkins.plugins.slack.SlackNotifier_-DescriptorImpl>
```

**Comment by timja** [comment]
Looks like a problem with the mail address resolvers, if you remove that I expect it will work

**Comment by mecseid** [comment]
Thanks, it works without the mail address resolver.
Should I close the issue and make another one, or continue this one:
Why the email resolver generates whole hudson configuration to plugin's configuration xml?

**Comment by jetersen** [comment]
@mecseid what version of the mailer plugin are you using?

**Comment by mecseid** [comment]
> @mecseid what version of the mailer plugin are you using?

1.32.1

**Comment by jetersen** [comment]
https://github.com/jenkinsci/mailer-plugin/blob/mailer-1.32.1/src/main/java/hudson/tasks/MailAddressResolver.java
Makes no sense why hudson would appear in the serialized as there is no mention of Jenkins/hudson model 🙈

**Comment by jetersen** [comment]
Might be some legacy thing from the `ExtensionPoint`
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/ExtensionPoint.java

**Comment by mecseid** [comment]
Should I have to create an issue in Jenkins JIRA or how can I help to move this issue forward?

**Comment by Jmennius** [comment]
Had the same issue - fixed by changing Slack plugin configuration back and forth in Jenkins instead of touching config file directly (toggled `User ID Resolver` setting and applied changes).
