### ISSUE TITLE
Error when "Include Custom Message" is checked

### ISSUE THREAD

**Issue by smann297** [jenkinsci/slack-plugin#747]
### Your checklist for this issue

- [x] Jenkins version 
2.274

- [x] Plugin version
2.45

- [x] OS
Linux

### Description

I am getting the following error when I have "Include Custom Message" checked. The error occurs with just a string (no variables) in the "Custom Message" text box. This started randomly occurring last week. 

```
[Slack Notifications] found #6894 as previous completed, non-aborted build
[Slack Notifications] will send OnSuccessNotification because build matches and user preferences allow it
ERROR: Build step failed with exception
java.lang.IllegalStateException
	at org.objectweb.asm.tree.analysis.BasicInterpreter.<init>(BasicInterpreter.java:66)
	at org.parboiled.transform.RuleMethodInterpreter.<init>(RuleMethodInterpreter.java:42)
	at org.parboiled.transform.InstructionGraphCreator.process(InstructionGraphCreator.java:41)
	at org.parboiled.transform.ParserTransformer.runMethodTransformers(ParserTransformer.java:62)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:45)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:39)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
Caused: java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:80)
	at org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:74)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expand(TokenMacro.java:199)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:237)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:211)
	at jenkins.plugins.slack.JenkinsTokenExpander.expand(JenkinsTokenExpander.java:22)
	at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.appendCustomMessage(ActiveNotifier.java:443)
	at jenkins.plugins.slack.ActiveNotifier.getBuildStatusMessage(ActiveNotifier.java:248)
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:125)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:607)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:187)
	at hudson.model.Run.execute(Run.java:1954)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Slack Notifications' marked build as failure
Finished: SUCCESS
```

**Comment by smann297** [comment]
<img width="950" alt="Screen Shot 2021-01-13 at 9 00 22 PM" src="https://user-images.githubusercontent.com/61983936/104534510-6b885a00-55e2-11eb-925d-89fa90284547.png">

**Comment by timja** [comment]
Update your token macro plugin version

**Comment by smann297** [comment]
Yep, that was it. Thanks!
