### ISSUE TITLE
Failed build notifications aren't being sent

### ISSUE THREAD

**Issue by NikolayMetchev** [jenkinsci/slack-plugin#75]
We are using Ivy for dependency management. This results in there being module builds for each jenkins project. For some reason build failures aren't going to slack. Only "back to normal" messages are being sent there.

**Comment by samrocketman** [comment]
When a build fails does Jenkins report it as failed?  If so then go into the job configuration and confirm failed build is checked one slack notifications.

**Comment by NikolayMetchev** [comment]
Yep. The email notification goes out saying the build has failed but the slack notification doesn't. Other slack notifications also work. It is just the failed build slack notification that isn't working.

**Comment by samrocketman** [comment]
Please provide slack plugin version and Jenkins version.  Also, any potentially related stack traces from logs.

**Comment by NikolayMetchev** [comment]
Slack plugin is 1.7. Jenkins version 1.606. 
Jenkins log contains only one stack trace. Not sure it is relevant: 

java.io.IOException: Unable to read /percentile/apps/jenkins/jobs/help/config.xml
	at hudson.XmlFile.read(XmlFile.java:144)
	at hudson.model.Items.load(Items.java:280)
	at jenkins.model.Jenkins$17.run(Jenkins.java:2673)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:903)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.thoughtworks.xstream.io.StreamException:  : input contained no data
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:126)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
	at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63)
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1053)
	at hudson.XmlFile.read(XmlFile.java:142)
	... 10 more
Caused by: java.io.EOFException: input contained no data
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 19 more

**Comment by NikolayMetchev** [comment]
/percentile/apps/jenkins/jobs/help/config.xml was an empty file so I moved it out of the way and the exception no longer shows up in the logs.

**Comment by NikolayMetchev** [comment]
Here is the relevant bit from the log file: 
Apr 01, 2015 3:34:25 PM INFO hudson.model.Run execute
testtwo/percentile:testtwo #48 main build action completed: FAILURE
Apr 01, 2015 3:34:26 PM WARNING jenkins.plugins.slack.ActiveNotifier completed
Project percentile:testtwo has no Slack configuration.
Apr 01, 2015 3:34:26 PM INFO hudson.model.Run execute
testtwo/percentile:testtwo-megabank #48 main build action completed: SUCCESS
Apr 01, 2015 3:34:26 PM WARNING jenkins.plugins.slack.ActiveNotifier completed
Project percentile:testtwo-megabank has no Slack configuration.

**Comment by NikolayMetchev** [comment]
![image](https://cloud.githubusercontent.com/assets/417373/6943324/25431c96-d885-11e4-89e6-7b684a5248e9.png)

![image](https://cloud.githubusercontent.com/assets/417373/6943339/3c2c9ba8-d885-11e4-85c4-bebf325f842f.png)

**Comment by NikolayMetchev** [comment]
Ok I see what has happened now. There seems to be separate configuration for modules and projects in Jenkins as far as slack is concerned. This doesn't seem to be the case for email notifications. It means that we have to go and configure each module separately if we want to use slack. We don't need to do that for email notifications.

**Comment by samrocketman** [comment]
It would be good if someone would contribute combining them.  So there's **only** the post build step and when you add that step you have to configure it as well.

**Comment by samrocketman** [comment]
I don't actively develop this project.  I only maintain pull requests and releases.  It would be great of someone could merge the UI so there's not so many moving parts.  That is the post-build step has configuration.

**Comment by tnguyen14** [comment]
I am running into issue where failed builds are not being notified as well.

**Comment by tonyjchong** [comment]
This happened to me as well. I initiated a job failure on purpose since I created the job.  I finally set to notify on success AND failure, changed the job to finally succeed, I then made the job fail and it started working. Odd....

**Comment by samrocketman** [comment]
In your case it doesn't notify repeated failures.  If you want that then you'll need to enable that option.

**Comment by rameshthoomu** [comment]
I also observed the same issue but after selecting "Notify Repeated Failure" it worked fine.. I see failure build notifications are triggering back to slack.

**Comment by timja** [comment]
should be fixed by moving to post build actions
