### ISSUE TITLE
Slack Send Message is working but Slack Response to Jenkins fails because of Invalid JSON response 

### ISSUE THREAD

**Issue by samgegr8** [jenkinsci/slack-plugin#771]
### Version report

Jenkins and plugins versions report:

```
Jenkins Version 2.289.1 
Plugin Version 2.48
```

### Reproduction steps

Pipeline Code 

```
 slackSend (color: '#9fe043', channel: "#ChannelName,message: "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

```

Jobs Log

```
ERROR: Slack notification failed with exception: ok
ERROR: Slack notification failed. See Jenkins logs for details.

```

Jenkins Log
```
Jul 05, 2021 9:45:56 AM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Slack post may have failed.  Invalid JSON response: ok
Jul 05, 2021 9:45:56 AM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Slack post may have failed. Response: ok
Jul 05, 2021 9:45:56 AM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
```

As per recent communication this has been fixed but it doesn't seem so in the recent version.

**Comment by timja** [comment]
You haven't said how you setup your slack integration, but I assume you aren't using bot user mode and I would suggest you do that instead as you'll have less issues:
https://github.com/jenkinsci/slack-plugin#bot-user-mode

**Comment by samgegr8** [comment]
Sorry for the incomplete information. In have set it up as a bot user mode itself.
<img width="1427" alt="Screenshot" src="https://user-images.githubusercontent.com/33149835/124465504-dc157400-ddd8-11eb-9843-49607e373f59.png">

Complete Jenkin Job logs and from there you can see that its setting the botuser

```
Slack Send Pipeline step running, values are - baseUrl: https://hooks.slack.com/services/XXXXXX/XXXXX/, teamDomain: <empty>, channel: #xxxx-xxxxx-xxxxx, color: #9fe043, botUser: true, tokenCredentialId: slack-xxxxxx-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
ERROR: Slack notification failed with exception: ok
ERROR: Slack notification failed. See Jenkins logs for details.

```

**Comment by timja** [comment]
Do not set a base url

**Comment by samgegr8** [comment]
```baseUrl``` is coming from the global configuration , which I cannot figure out. Can you help me here with it

**Comment by timja** [comment]
Remove the override url, it's in your screen shot

**Comment by samgegr8** [comment]
Hey Removing the override url makes it to fail the steps

Jenkins Log

```
Error posting to Slack
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:476)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
Also:   java.net.SocketException: Broken pipe (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:381)
Caused: javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:350)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:293)```

Pipeline Job Logs 

```
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: <empty>, channel: #dosa-alerts-jenkins, color: #9fe043, botUser: true, tokenCredentialId: slack-integration-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
ERROR: Slack notification failed. See Jenkins logs for details.
[Pipeline] sh
```

**Comment by timja** [comment]
You need to set the workspace as well

**Comment by samgegr8** [comment]
I did that and I tested it from the Jenkins by Clicking on the `Test Connection`. It fails and the Jenkins log is same as above. I can try by running the job but would there be any difference ?

**Comment by samgegr8** [comment]
Now we are getting this error 

```
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: XXXXX, channel: #dosa-alerts-jenkins, color: #9fe043, botUser: true, tokenCredentialId: slack-integration-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
ERROR: Slack notification failed. See Jenkins logs for details.

```

**Comment by timja** [comment]
check the logs, have you invited the bot to your channel?
