### ISSUE TITLE
java.lang.NullPointerException with jenkins 1.560

### ISSUE THREAD

**Issue by tru** [jenkinsci/slack-plugin#8]
Have a lot of these in my log after upgrade to 1.560.

```
Apr 22, 2014 8:26:38 AM hudson.model.listeners.RunListener report
WARNING: RunListener failed
java.lang.NullPointerException
        at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:65)
        at jenkins.plugins.slack.SlackListener.onCompleted(SlackListener.java:26)
        at jenkins.plugins.slack.SlackListener.onCompleted(SlackListener.java:14)
        at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:199)
        at hudson.model.Run.execute(Run.java:1753)
        at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
        at hudson.model.ResourceController.execute(ResourceController.java:88)
        at hudson.model.Executor.run(Executor.java:231)
```

**Comment by chrismeyersfsu** [comment]
Also getting with Jenkins 1.598

**Comment by samrocketman** [comment]
@chrismeyersfsu Please try the latest 1.7 snapshot.  The current build of the slack plugin is stable.  JDK 1.7 and Maven should be installed.

To build:

```
mvn test && mvn package
```

Then install the `target/slack.hpi` file in Jenkins.  Please let me know how it works with the latest.  A release is coming soon.

**Comment by samrocketman** [comment]
@chrismeyersfsu Also please provide more info.  What version of the slack plugin do you have installed?

**Comment by samrocketman** [comment]
In fact, after comparing the source of the slack 1.6 plugin with the original stack trace I believe #35 fixes this issue by ensuring `jobProperty` is not null.

**Comment by samrocketman** [comment]
Slack Plugin 1.7 has been released.  This a fix for this has been included in it.  Please try out new version and if it doesn't resolved this issue then ask for this to be re-opened and provide more details.
