### ISSUE TITLE
java 8 support - ssl issue

### ISSUE THREAD

**Issue by charlesivie** [jenkinsci/slack-plugin#86]
When the plugin calls slack, the following error occurs;
 java.security.InvalidKeyException: ECDH key agreement requires ECPublicKey for doPhase

The plugin doesn't work with jenkins, java 8 on AWS linux for me, below is the stack trace. 

Reverting to java7 fix's the issue, but I need java 8.

Any ideas?

osting: to #sparqlr on sparqlr using https://sparqlr.slack.com/services/hooks/jenkins-ci?token=wZoz9KQc0rVN3sECZ8G9qZum: sparqlr-api-release - #136 Started by changes from tomcat (2 file(s) changed) (</job/sparqlr-api-release/136/|Open>) good
29-Apr-2015 12:20:13.132 INFO [Executor #1 for master : executing sparqlr-api-release #136] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry I/O exception (javax.net.ssl.SSLException) caught when processing request: java.lang.RuntimeException: Could not generate secret
29-Apr-2015 12:20:13.133 INFO [Executor #1 for master : executing sparqlr-api-release #136] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry Retrying request
29-Apr-2015 12:20:13.363 INFO [Executor #1 for master : executing sparqlr-api-release #136] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry I/O exception (javax.net.ssl.SSLException) caught when processing request: java.lang.RuntimeException: Could not generate secret
29-Apr-2015 12:20:13.363 INFO [Executor #1 for master : executing sparqlr-api-release #136] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry Retrying request
29-Apr-2015 12:20:13.573 INFO [Executor #1 for master : executing sparqlr-api-release #136] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry I/O exception (javax.net.ssl.SSLException) caught when processing request: java.lang.RuntimeException: Could not generate secret
29-Apr-2015 12:20:13.574 INFO [Executor #1 for master : executing sparqlr-api-release #136] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry Retrying request
29-Apr-2015 12:20:13.765 WARNING [Executor #1 for master : executing sparqlr-api-release #136] null.null Error posting to Slack
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate secret
at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1894)
at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1877)
at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1803)
at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:128)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:506)
at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:66)
at jenkins.plugins.slack.ActiveNotifier.notifyStart(ActiveNotifier.java:65)
at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:49)
at jenkins.plugins.slack.SlackNotifier$SlackJobProperty.prebuild(SlackNotifier.java:280)
at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:816)
at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:811)
at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:807)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
at hudson.model.Run.execute(Run.java:1741)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:374)
Caused by: java.lang.RuntimeException: Could not generate secret
at sun.security.ssl.ECDHCrypt.getAgreedSecret(ECDHCrypt.java:98)
at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1036)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:344)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:957)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:892)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:735)
at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
... 21 more
Caused by: java.security.InvalidKeyException: ECDH key agreement requires ECPublicKey for doPhase
at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi.engineDoPhase(Unknown Source)
at javax.crypto.KeyAgreement.doPhase(KeyAgreement.java:552)
at sun.security.ssl.ECDHCrypt.getAgreedSecret(ECDHCrypt.java:95)
... 29 more

**Comment by samrocketman** [comment]
Hello, contributions are welcome to fix this issue.  I do not develop this plugin.  I only maintain pull requests and releases.

When you say "need" Java 8 do you mean the software you're building is Java 8?  Because Jenkins on Java 7  can still build Java 8 software.

**Comment by thetis15** [comment]
i changed jdk vender openjdk to oracle.
check your jdk vender

**Comment by dstainer** [comment]
@samrocketman this isn't a plugin issue, in my experience with this issue it was tied to OpenJDK. We moved to OpenJDK for Java 8. Not only did the Slack plugin fail, but also the email-ext (it too complained of SSL issues). At issue I believe was the non-existence of encryption related providers.

The temporary solution for us, that allowed us to use Java 8 with Jenkins, the Slack Plugin and Email-Ext was to disable ECC with the following start up flag: -Dcom.sun.net.ssl.enableECC=false

**Comment by samrocketman** [comment]
I wonder if adding the Java Cryptography Extension (JCE) unlimited strength would resolve the issue.  I recall when my company migrated to TLS 1.2 only that extra things had to be configured and JCE was one of them.  http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by samrocketman** [comment]
Should this issue remain an issue?  I feel it should be marked as invalid and closed since I don't think it's actually a problem with the slack plugin since this affects multiple plugins in your instance.

Additionally, why do you need Jenkins to be Java 8?  Jenkins using Java 1.7 can still build Java 1.8 projects just fine.  Please let me know.

**Comment by charlesivie** [comment]
yes i agree, closeable 😀
