### ISSUE TITLE
java.net.UnknownHostException: slack.com posting message as bot user

### ISSUE THREAD

**Issue by demurray** [jenkinsci/slack-plugin#901]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.375.3
OS: Linux - 5.15.0-1014-aws
Java: 11.0.18 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
ansicolor:1.0.2
ant:481.v7b_09e538fcca
antisamy-markup-formatter:159.v25b_c67cd35fb_
apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
artifactory:3.18.0
authentication-tokens:1.4
authorize-project:1.4.0
aws-credentials:191.vcb_f183ce58b_9
aws-java-sdk:1.12.406-370.v8f993c987059
aws-java-sdk-cloudformation:1.12.406-370.v8f993c987059
aws-java-sdk-codebuild:1.12.406-370.v8f993c987059
aws-java-sdk-ec2:1.12.406-370.v8f993c987059
aws-java-sdk-ecr:1.12.406-370.v8f993c987059
aws-java-sdk-ecs:1.12.406-370.v8f993c987059
aws-java-sdk-efs:1.12.406-370.v8f993c987059
aws-java-sdk-elasticbeanstalk:1.12.406-370.v8f993c987059
aws-java-sdk-iam:1.12.406-370.v8f993c987059
aws-java-sdk-logs:1.12.406-370.v8f993c987059
aws-java-sdk-minimal:1.12.406-370.v8f993c987059
aws-java-sdk-sns:1.12.406-370.v8f993c987059
aws-java-sdk-sqs:1.12.406-370.v8f993c987059
aws-java-sdk-ssm:1.12.406-370.v8f993c987059
badge:1.9.1
basic-branch-build-strategies:71.vc1421f89888e
blueocean:1.26.0
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.26.0
blueocean-commons:1.27.2
blueocean-config:1.27.2
blueocean-core-js:1.27.2
blueocean-dashboard:1.27.2
blueocean-display-url:2.4.1
blueocean-events:1.26.0
blueocean-git-pipeline:1.26.0
blueocean-github-pipeline:1.26.0
blueocean-i18n:1.27.2
blueocean-jira:1.27.2
blueocean-jwt:1.27.2
blueocean-personalization:1.27.2
blueocean-pipeline-api-impl:1.26.0
blueocean-pipeline-editor:1.26.0
blueocean-pipeline-scm-api:1.27.2
blueocean-rest:1.27.2
blueocean-rest-impl:1.27.2
blueocean-web:1.27.2
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.1-3
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
build-blocker-plugin:1.7.8
build-name-setter:2.2.0
build-timeout:1.28
build-timestamp:1.0.3
build-token-root:151.va_e52fe3215fc
cache-monitor:1.0.0
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
call-remote-job-plugin:1.0.21
checks-api:1.8.1
cloudbees-bitbucket-branch-source:796.v6cb_1559e1673
cloudbees-disk-usage-simple:178.v1a_4d2f6359a_8
cloudbees-folder:6.815.v0dd5a_cb_40e0e
command-launcher:90.v669d7ccb_7c31
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
config-file-provider:3.11.1
configuration-as-code:1569.vb_72405b_80249
configurationslicing:430.v966357576543
copyartifact:686.v6fd37018d7c2
credentials:1224.vc23ca_a_9a_2cb_0
credentials-binding:523.vd859a_4b_122e6
custom-tools-plugin:0.8
dark-theme:315.va_22e7d692ea_a
data-tables-api:1.12.1-4
display-url-api:2.3.7
docker-commons:419.v8e3cd84ef49c
docker-workflow:563.vd5d2e5c4007f
durable-task:504.vb10d1ae5ba2f
echarts-api:5.4.0-1
email-ext:2.95
envinject:2.901.v0038b_6471582
envinject-api:1.199.v3ce31253ed13
es-audit-logger:1.0.0
extended-choice-parameter:359.v35dcfdd0c20d
extended-read-permission:3.2
external-monitor-job:203.v683c09d993b_9
extra-columns:1.25
favorite:2.4.1
file-operations:1.11
flexible-publish:0.16.1
font-awesome-api:6.2.1-1
ghprb:1.42.2
git:4.14.3
git-changelog:3.29
git-client:3.13.1
git-server:99.va_0826a_b_cdfa_d
github:1.36.1
github-api:1.303-417.ve35d9dd78549
github-branch-source:3.13.2-nike
gradle:2.3.2
gravatar:2.2
groovy-postbuild:2.5
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.31
http_request:1.15
inode-monitor:1.0.1
instance-identity:142.v04572ca_5b_265
ionicons-api:45.vf54fca_5d2154
ivy:2.4
jackson2-api:2.14.2-319.v37853346a_229
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:63.v62d2fd4b_4793
jenkins-design-language:1.27.2
jersey2-api:2.38-1
jira:3.9
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.16-2
job-dsl:1.77
jobConfigHistory:1207.vd28a_54732f92
jquery:1.12.4-1
jquery3-api:3.6.1-2
jsch:0.1.55.61.va_e9ee26616e7
junit:1198.ve38db_d1b_c975
kerberos-sso:1.11
ldap:671.v2a_9192a_7419d
ldapemail:0.8
lockable-resources:1131.vb_7c3d377e723
mailer:448.v5b_97805e3767
mapdb-api:1.0.9.0
mask-passwords:150.vf80d33113e80
matrix-auth:2.6.8
matrix-project:785.v06b_7f47b_c631
maven-plugin:3.21
metrics:4.2.13-420.vea_2f17932dd6
mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
monitoring:1.92.0
nant:248.vcc8a_3eec8db_a
next-build-number:1.8
nike-bmx-agent-manager-plugin:0.0.31
nike-cerberus-plugin:1.0.5
okhttp-api:4.10.0-132.v7a_7b_91cef39c
packer:1.5
pam-auth:1.10
percentage-du-node-column:0.1.0
pipeline-aws:1.43
pipeline-build-step:486.vd08f550cceee
pipeline-github-lib:38.v445716ea_edda_
pipeline-githubnotify-step:49.vf37bf92d2bc8
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-rest-api:2.31
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
pipeline-stage-view:2.31
pipeline-utility-steps:2.15.1
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:2.20.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
postbuild-task:1.9
pubsub-light:1.17
rebuild:1.34
remote-file:1.23
resource-disposer:0.21
reverse-proxy-auth-plugin:1.7.4
role-strategy:587.v2872c41fa_e51
run-condition:1.5
saml:2.333.vc81e525974a_c
scm-api:631.v9143df5b_e4a_a
script-security:1229.v4880b_b_e905a_6
self-service-plugin:1.0.0
simple-theme-plugin:146.v0e67db_a_9052e
slack:664.vc9a_90f8b_c24a_
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
sonar:2.15
sse-gateway:1.26
ssh-agent:327.v230ecd01f86f
ssh-credentials:305.v8f4381501156
ssh-slaves:1.821.vd834f8a_c390e
sshd:3.275.v9e17c10f2571
structs:324.va_f5d6774f3a_d
subversion:2.17.1
theme-manager:1.6
thinBackup:1.15
throttle-concurrents:2.11
timestamper:1.22
token-macro:321.vd7cc1f2a_52c8
translation:1.16
trilead-api:1.67.vc3938a_35172f
uno-choice:2.6.4
url-auth-sso:1.0
variant:59.vf075fe829ccb
windows-slaves:1.8.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:1010.vf7a_b_98e847c1
workflow-cps:3641.vf58904a_b_b_5d8
workflow-durable-task-step:1234.v019404b_3832a
workflow-job:1284.v2fe8ed4573d4
workflow-multibranch:733.v109046189126
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
ws-cleanup:0.44
xvfb:1.2
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Agent:
```text
os.arch | amd64
os.name | Linux
os.version | 5.15.0-1014-aws
java.runtime.version | 11.0.18+10-post-Ubuntu-0ubuntu120.04.1
```

Builds run with container based on `node:16.18.1-alpine`.

### Reproduction steps

1. Slack plugin configured with workspace name, credential for custom app, custom slack app bot user checked.
2. Run build that makes call to `slackSend`

### Expected Results

Message posted to Slack successfully as bot user.

### Actual Results

Call fails with log output below.

```text
May 11, 2023 7:09:43 AM FINE jenkins.plugins.slack.StandardSlackService
Posting: to #channel-name on teamdomain:  {"attachments":[{"fallback":"*<https://job-url | #1092>* *dam-meta* (master) | Starting build...","color":"good","fields":[{"short":false,"value":"*<https://job-url | #1092>* *dam-meta* (master) | Starting build..."}],"mrkdwn_in":["pretext","text","fields"]}],"link_names":"1","unfurl_links":"true","unfurl_media":"true","channel":"#channel-name","as_user":"true"}
May 11, 2023 7:09:48 AM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Error posting to Slack
java.net.UnknownHostException: slack.com: Try again
    at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
    at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
    at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
    at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
    at java.base/java.net.InetAddress.getAllByName(Unknown Source)
    at java.base/java.net.InetAddress.getAllByName(Unknown Source)
    at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
    at jenkins.plugins.slack.StandardSlackService.postToSlack(StandardSlackService.java:214)
    at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:340)
    at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:379)
    at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:351)
```

On a second call, where we try to post the build failure to Slack, the stack trace is as follows:

```text
May 11, 2023 7:09:50 AM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Error posting to Slack
java.net.UnknownHostException: slack.com
	at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at jenkins.plugins.slack.StandardSlackService.postToSlack(StandardSlackService.java:214)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:340)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:379)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:351)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:359)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:258)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Anything else?

This integration had been working for over a year, and started to fail around Thursday, May 4 with no apparent code or configuration change.

In the [other issues](https://github.com/jenkinsci/slack-plugin/issues?q=is%3Aissue+UnknownHostException+is%3Aclosed) with `UnknownHostException`, it looks like folks are in the non-bot user branch and did not have a team domain set. We are on the code path [here](https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L205) for a bot user, and pass credentials for a custom Slack app.

We can run a command `dig slack.com` on the build agent and get output:

```text
; <<>> DiG 9.16.1-Ubuntu <<>> slack.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24275
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;slack.com.			IN	A

;; ANSWER SECTION:
slack.com.		35	IN	A	44.237.180.172
slack.com.		35	IN	A	35.82.91.193
slack.com.		35	IN	A	52.89.90.67
slack.com.		35	IN	A	35.81.85.251
slack.com.		35	IN	A	54.71.95.193
slack.com.		35	IN	A	54.188.33.22
slack.com.		35	IN	A	44.234.235.93
slack.com.		35	IN	A	54.70.179.16
slack.com.		35	IN	A	54.245.50.245

;; Query time: 12 msec
;; SERVER: 10.9.8.7#53(10.9.8.7)
;; WHEN: Tue May 09 19:04:16 UTC 2023
;; MSG SIZE  rcvd: 182
```

**Comment by timja** [comment]
This must be something local to your setup, can you write a small Java program and run it on the same VM and make sure you can resolve slack.com? 

In case the Java resolver is resolving differently to dig.

Is this consistent and still happening?

**Comment by thomasvincent** [comment]
Here is a small Java program that you can use to test if you can resolve slack.com:
 ```
 import java.net.InetAddress;

public class Test {

    public static void main(String[] args) throws Exception {
        InetAddress address = InetAddress.getByName("slack.com");
        System.out.println(address);
    }

}

```

**Comment by mallik30** [comment]
for me it returns following "Exception in thread "main" java.net.UnknownHostException: slack.com: nodename nor servname provided, or not known"
how to resolve this?
