### ISSUE TITLE
NPE on SlackNotification

### ISSUE THREAD

**Issue by johnjelinek** [jenkinsci/slack-plugin#933]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.401.1
OS: Linux - 5.10.176+
Java: 11.0.19 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
Parameterized-Remote-Trigger:3.2.0
ace-editor:1.1
additional-metrics:67.vcb_823d3999a_2
allure-jenkins-plugin:2.31.1
analysis-core:1.80
analysis-model-api:11.11.0
ansicolor:1.0.4
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.2.1-1.1
async-http-client:1.9.40.0
authentication-tokens:1.53.v1c90fd9191a_b_
autograding:4.1.0
basic-branch-build-strategies:81.v05e333931c7d
blueocean:1.27.5.1
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.5.1
blueocean-commons:1.27.5.1
blueocean-config:1.27.5.1
blueocean-core-js:1.27.5.1
blueocean-dashboard:1.27.5.1
blueocean-display-url:2.4.2
blueocean-events:1.27.5.1
blueocean-git-pipeline:1.27.5.1
blueocean-github-pipeline:1.27.5.1
blueocean-i18n:1.27.5.1
blueocean-jira:1.27.5.1
blueocean-jwt:1.27.5.1
blueocean-personalization:1.27.5.1
blueocean-pipeline-api-impl:1.27.5.1
blueocean-pipeline-editor:1.27.5.1
blueocean-pipeline-scm-api:1.27.5.1
blueocean-rest:1.27.5.1
blueocean-rest-impl:1.27.5.1
blueocean-web:1.27.5.1
bootstrap5-api:5.3.2-2
bouncycastle-api:2.29
branch-api:2.1128.v717130d4f816
build-user-vars-plugin:1.9
caffeine-api:3.1.8-133.v17b_1ff2e0599
cctray-xml:76.v04864da_fa_92c
checks-api:2.0.2
cloud-stats:320.v96b_65297a_4b_b_
cloudbees-bitbucket-branch-source:848.v42c6a_317eda_e
cloudbees-disk-usage-simple:187.v6378d330d1d4
cloudbees-folder:6.858.v898218f3609d
cobertura:1.17
code-coverage-api:4.99.0
command-launcher:107.v773860566e2e
commons-httpclient3-api:3.1-3
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.10.0-78.v3e7b_ea_d5a_fe1
conditional-buildstep:1.4.3
config-file-provider:959.vcff671a_4518b_
configuration-as-code:1700.v6f448841296e
coverage:1.2.0
credentials:1293.vff276f713473
credentials-binding:642.v737c34dea_6c2
cucumber-reports:5.8.0
dashboard-view:2.495.v07e81500c3f2
data-tables-api:1.13.6-5
database:191.vd5981b_97a_5fa_
database-mysql:1.4
datadog:5.5.1
discard-old-build:1.07
display-url-api:2.200.vb_9327d658781
docker-commons:439.va_3cb_0a_6a_fb_29
docker-slaves:1.0.7
docker-workflow:572.v950f58993843
durable-task:523.va_a_22cf15d5e0
echarts-api:5.4.0-7
email-ext:2.102
embeddable-build-status:412.v09da_db_1dee68
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
external-monitor-job:215.v2e88e894db_f8
favorite:2.4.3
flaky-test-handler:1.2.3
flexible-publish:0.16.1
font-awesome-api:6.4.2-1
forensics-api:2.3.0
generic-webhook-trigger:1.88.0
git:5.2.0
git-client:4.5.0
git-server:99.va_0826a_b_cdfa_d
github:1.37.3.1
github-api:1.316-451.v15738eef3414
github-branch-source:1741.va_3028eb_9fd21
github-pullrequest:0.5.0
gitlab-plugin:1.7.16
google-compute-engine:4.3.17
google-oauth-plugin:1.318.vb_39c5db_e3041
gradle:2.9
h2-api:11.1.4.199-12.v9f4244395f7a_
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.32
http_request:1.18
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
ivytrigger:1.00
jackson2-api:2.15.3-363.v82c51b_de9f60
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jenkins-design-language:1.27.5.1
jersey2-api:2.40-1
jgiven:0.15.1
jira:3.11
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.18-1
job-dsl:1.87
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.7.1-1
jsch:0.2.8-65.v052c39de79b_2
junit:1240.vf9529b_881428
junit-attachments:167.vf1d139e316b_3
kubernetes:4054.v2da_8e2794884
kubernetes-client-api:6.8.1-224.vd388fca_4db_3b_
kubernetes-credentials:0.11
label-linked-jobs:6.0.1
ldap:711.vb_d1a_491714dc
lockable-resources:1185.v0c528656ce04
mailer:463.vedf8358e006b_
managed-scripts:1.5.6
mask-passwords:173.v6a_077a_291eb_5
matrix-auth:3.2.1
matrix-project:818.v7eb_e657db_924
maven-dependency-update-trigger:1.5
maven-deployment-linker:1.5.1
maven-plugin:3.23
mercurial:1260.vdfb_723cdcc81
metrics:4.2.18-442.v02e107157925
metrics-datadog:1.0
mina-sshd-api-common:2.11.0-86.v836f585d47fa_
mina-sshd-api-core:2.11.0-86.v836f585d47fa_
monitoring:1.95.0
multibranch-build-strategy-extension:1.0.10
mysql-api:8.0.16
naginator:1.421.v85c11e2db_507
nested-view:1.33
next-build-number:1.8
node-iterator-api:55.v3b_77d4032326
nodejs:1.6.1
oauth-credentials:0.646.v02b_66dc03d2e
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
pagerduty:0.7.1
pam-auth:1.10
parameterized-trigger:2.46
performance:947.v71d3163a_3512
pipeline-build-step:505.v5f0844d8d126
pipeline-github:2.8-155.8eab375ac9f8
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-maven:1345.va_0ef5530a_5ca_
pipeline-maven-api:1345.va_0ef5530a_5ca_
pipeline-maven-database:1345.va_0ef5530a_5ca_
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2144.v077a_d1928a_40
pipeline-model-definition:2.2144.v077a_d1928a_40
pipeline-model-extensions:2.2144.v077a_d1928a_40
pipeline-npm:95.v5213efa_9585f
pipeline-rest-api:2.33
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2144.v077a_d1928a_40
pipeline-stage-view:2.33
pipeline-utility-steps:2.16.0
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.6.0
prism-api:1.29.0-8
prometheus:2.3.3
promoted-builds:936.va_571a_a_b_f8da_5
pubsub-light:1.18
purge-build-queue-plugin:88.v23b_97b_f2c7a_d
rake:1.8.0
rebuild:320.v5a_0933a_e7d61
rubyMetrics:1.6.5
run-condition:1.7
saml:4.429.v9a_781a_61f1da_
scm-api:676.v886669a_199a_a_
script-security:1275.v23895f409fb_d
simple-theme-plugin:160.vb_76454b_67900
slack:684.v833089650554
snakeyaml-api:2.2-111.vc6598e30cc65
snyk-security-scanner:4.0.2
sonar:2.16.1
sse-gateway:1.26
ssh-agent:333.v878b_53c89511
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.916.vd17b_43357ce4
sshd:3.312.v1c601b_c83b_0e
strict-crumb-issuer:2.1.1
structs:325.vcb_307d2a_2782
test-results-analyzer:0.4.0
token-macro:384.vf35b_f26814ec
trilead-api:2.84.v72119de229b_7
variant:60.v7290fc0eb_b_cd
warnings-ng:10.5.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1283.v99c10937efcb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3806.va_3a_6988277b_2
workflow-durable-task-step:1289.v4d3e7b_01546b_
workflow-job:1326.ve643e00e9220
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d
xtrigger-api:1.0
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller: Debian GNU/Linux 11
Agents: Ubuntu 22.04

### Reproduction steps

1. Reload job config from JCasC
2. Run job
3. Watch error
4. Save job in UI
5. Watch success

### Expected Results

```java
[Slack Notifications] found #33 as previous completed, non-aborted build
[Slack Notifications] will send OnSuccessNotification because build matches and user preferences allow it
Finished: SUCCESS
```

### Actual Results

```java
[Slack Notifications] found #33 as previous completed, non-aborted build
[Slack Notifications] will send OnSuccessNotification because build matches and user preferences allow it
ERROR: Build step failed with exception
java.lang.NullPointerException
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:127)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:607)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:189)
	at hudson.model.Run.execute(Run.java:1947)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Build step 'Slack Notifications' marked build as failure
```
or
```java
[Slack Notifications] found #33 as previous completed, non-aborted build
[Slack Notifications] will send OnEveryFailureNotification because build matches and user preferences allow it
ERROR: Build step failed with exception
java.lang.NullPointerException
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:127)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:607)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:189)
	at hudson.model.Run.execute(Run.java:1947)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Build step 'Slack Notifications' marked build as failure
```

### Anything else?

```groovy
slackNotifier {
   notifySuccess(true)
   notifyEveryFailure(true)
   includeCustomMessage(true)
   customMessageSuccess(':scissors: cutting staging: $GIT_STAGING_RELEASE_BRANCH')
   customMessageFailure(':scissors: staging - Failure \n $BUILD_NUMBER')
   teamDomain('liveramp')
   tokenCredentialId('redacted')
   iconEmoji(':scissors:')
   room('#release')
}
```

**Comment by timja** [comment]
I assume a mandatory field isn't set.
Have you tried saving from the UI and comparing the xml?

**Comment by johnjelinek** [comment]
I have tried saving from the UI, but the XML doesn't seem to be viewable for job definitions. I am going to try setting `commitInfoChoice('NONE')`

**Comment by johnjelinek** [comment]
It appears like setting `commitInfoChoice('NONE')` fixed it on my end. Is there a better error message that can be provided to handle this situation better?

**Comment by timja** [comment]
Unsure I haven't looked into jobdsl much but that's a required parameter that would also be set using the UI.

(you aren't the first to hit it but haven't seen it in quite a long time as a lot of people use pipelines these days)
